### ISSUE TITLE
don't support chinese????

### ISSUE THREAD

**Issue by zeroandexe** [troldal/OpenXLSX#1]
i use your library, write chinese in cell and create a xlsx , so using excel to open the file ,but it warning me that file is  damaged;

**Comment by troldal** [comment]
I guess you resolved it yourself, since you closed this issue?

**Comment by zeroandexe** [comment]
yeah，the question is about charset , it need UTF8  but not need gbk2312 , i use gbk2312 frist.
and , the error file is "./xl/worksheets/sheet1.xml" in xlsx，when i launch excel to open the file  , it give me error.
so, i see your code and think the question of excel  that need to  recognize words of cell , but gbk2312 is incompatible in excel.

thank you
