### ISSUE TITLE
terminating with uncaught exception of type Zippy::ZipRuntimeError: file open failed

### ISSUE THREAD

**Issue by accsky** [troldal/OpenXLSX#100]
I want to writie to android device's sdcard. Why?

**Comment by jorgeberjano** [comment]
In windows, with the library compiled in static (lib) or shared (dll) mode when try to execute:
```
XLDocument document;
document.create("c:/Demo01.xlsx");

```
It throws the exception Zippy::ZipRuntimeError.

**Comment by troldal** [comment]
I did some cleanup of the project. Among other things, the OpenXLSX library is now self-contained in the OpenXLSX subfolder. Also, only one library is being built: shared or static. But not both. You can select which one in the CMakeLists.txt. Finally, the library is in a namespace called OpenXLSX. Hence, the full name in CMake is OpenXLSX::OpenXLSX.

All demo programs have been updated accordingly.

Regarding Android devices: I haven't tested the library on Android, so you are on your own...

**Comment by nesc999** [comment]
If Zippy::ZipRuntimeError still show up, try to set your project'a attribution -> C/C++ -> Coding generation -> execution library ->/MTd.
It work for me at least.
