### ISSUE TITLE
XLWorkbook setSheetIndex wrong

### ISSUE THREAD

**Issue by WuyangPeng** [troldal/OpenXLSX#106]
if (index == std::distance(xmlDocument().document_element().child("sheets").children().begin(),
                               std::find_if(xmlDocument().document_element().child("sheets").children().begin(),
                                            xmlDocument().document_element().child("sheets").children().end(),
                                            [&](const XMLNode& item) { return sheetName == item.attribute("name").value(); })))
        return;

That's right index - 1

**Comment by troldal** [comment]
Not sure what the issue is here, so I'm closing it.

**Comment by WuyangPeng** [comment]
i mean in function  void XLWorkbook::setSheetIndex(const std::string& sheetName, unsigned int index)

if (index == std::distance(xmlDocument().document_element().child("sheets").children().begin(),

should be

if (index - 1 == std::distance(xmlDocument().document_element().child("sheets").children().begin(),

**Comment by troldal** [comment]
Yes, you are right. Good catch.
I have updated the master branch, and will issue a new release soon.
