### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by uLuckLess** [troldal/OpenXLSX#108]
Hi there.

Cannot open XLSX file. Unfortunately I cannot share the file due to it has a lot of personal info inside, and when I delete it and resave with excel - it kinda starts to open. This is a file that's auto generated by online banking system, so there might be some specifics.

I will try to give you as much context as possible to solve it.

Everything is crashed in function 
uint32_t GetNewRelsID(XMLNode relationshipsNode)

stack is 
>	XXX.exe!``anonymous namespace'::GetNewRelsID'::`2'::<lambda_1>::operator()(pugi::xml_node a, pugi::xml_node b) Line 167	C++
 	[External Code]	
 	XXX.exe!`anonymous namespace'::GetNewRelsID(pugi::xml_node relationshipsNode) Line 164	C++
 	XXX.exe!OpenXLSX::XLRelationships::addRelationship(OpenXLSX::XLRelationshipType type, const std::string & target) Line 272	C++
 	XXX.exe!OpenXLSX::XLDocument::executeCommand<OpenXLSX::XLCommandAddSharedStrings>(OpenXLSX::XLCommandAddSharedStrings command) Line 277	C++
 	XXX.exe!OpenXLSX::XLDocument::open(const std::string & fileName) Line 470	C++
 	XXX.exe!OpenXLSX::XLDocument::XLDocument(const std::string & docPath) Line 432	C++

The problem is that 
b._root->first_attribute->value == "rIdSt"
substring is "St" which is not a number and stoi generates exception

**Comment by troldal** [comment]
It's difficult to know what's going on without the spreadsheet you are working on, but fully I understand that you don't want to share a spreadsheet full of personal info. Instead, try this:

1. Change the file extension of the spreadsheet file from .xlsx to .zip
2. Open the file in WinZip (or a similar app)
3. In the file tree inside the .zip file, navigate to xl/worksheets
4. Delete all the files in the worksheets folder (usually called "sheet1.xml" or similar). These files contain all the sheet data, i.e. all personal information you don't want to share.
5. Save the .zip file, and change the extension to .xlsx

After doing this, the file is no longer a valid Excel spreadsheet (i.e., it can't be opened in Excel), but that doesn't matter; I want to look in some of the other .xml files inside the spreadsheet. And all your personal information has been removed.

<img width="859" alt="screenshot" src="https://user-images.githubusercontent.com/1604351/137779359-bde0c999-baed-4859-8718-ac4d16cc5581.png">

If you can do that and share the file with me, it will be a great help.
