### ISSUE TITLE
Add function to read/write cell background color

### ISSUE THREAD

**Issue by sp00ktober** [troldal/OpenXLSX#109]
Hello :)

Maybe i just did not find it but it seems there is no way to actually get the background color of a specific cell.
It would be really nice to have this ability.

But beside that its a really nice lib to work with xlsx files, super easy to use! Thanks for the work.

**Comment by aral-matrix** [comment]
@sp00ktober: in case you were still waiting - I have nearly completed implementation & will soon submit it to @troldal for approval and integration into the repo.

**Comment by aral-matrix** [comment]
aaand the new functionality is implemented in [XLStyles](https://github.com/troldal/OpenXLSX/blob/master/OpenXLSX/headers/XLStyles.hpp) and XLCell::cellFormat / XLCell::setCellFormat. XLRow and XLColumn also have "format()" and "setFormat()" functions, please see ```Demo10``` for examples on how to use this functionality.
