### ISSUE TITLE
Can the library evaluate Excel formula when reading + return type of cell data?

### ISSUE THREAD

**Issue by stu0408** [troldal/OpenXLSX#117]
Hi,

I am interested to try out the OpenXLSX library for reading and writing data from/to XLSX.

### Q1. Can the library evaluate excel formulas?
If e.g. a cell contains a formula "=2+3". 
When reading, will the OpenXLSX library return a number (5) or a string ("=2+3")? Or can it do both?

---

### Q2. Can the library return the type of the cell data (float, string...)
If yes - which types are supported yet?

---

In the documentation I could not find this information.

Thanks,
STU

**Comment by troldal** [comment]
Hi @stu0408,

Regarding your first question, the answer is no. OpenXLSX does not evaluate cell formulas, and to be honest it's not something I intend to implement. Formulas can be very long and complicated, so implementing cell formula evaluation is almost like implementing a parser for a programming language. If someone else wants to implement it, I will be happy to merge into the project, but it's not something I'm going to do. Also, I know of no other Excel library (in any programming language) that supports formula evaluation, which indicates that it is a complicated matter and/or it's not something a lot of people need.

As for your second question, the answer is yes. You can access it through the XLCellValue class. E.g., if you have an XLCell object called myCell, you can do the following:
```cpp
auto cellType = myCell.value().type();

```
 This returns an XLValueType enum, which has the following possible values:

```cpp
enum class XLValueType { Empty, Boolean, Integer, Float, Error, String };
```

/Kenneth

**Comment by stu0408** [comment]
Hi @troldal ,

thank you very much for the quick response. This helps further.

----

"_Also, I know of no other Excel library (in any programming language) that supports formula evaluation, which indicates that it is a complicated matter and/or it's not something a lot of people need._"

The OpenPyXl library can do it, also the Aspose.Cells.

https://openpyxl.readthedocs.io/en/stable/api/openpyxl.reader.excel.html => (`data_only=True`)
`classopenpyxl.reader.excel.ExcelReader(fn, read_only=False, keep_vba=False, data_only=False, keep_links=True`

Parameters:	

- filename (string or a file-like object open in binary mode c.f., zipfile.ZipFile) – the path to open or a file-like object
- read_only (bool) – optimised for reading, content cannot be edited
- keep_vba (bool) – preseve vba content (this does NOT mean you can use it)
- **data_only (bool) – controls whether cells with formulae have either the formula (default) or the value stored the last time Excel read the sheet**
- keep_links (bool) – whether links to external workbooks should be preserved. The default is True

Kind regards,
STU

**Comment by troldal** [comment]
Interesting. I didn't know that. 

With the pricetag on the Aspose.Cells library, I guess they have a lot more resources to implement that kind of functionality. But I'm impressed that OpenPyXl can do it (although it is only limited support for formula evaluation), considering that it is an open-source library.

**Comment by stu0408** [comment]
Yes, it is a cool feature. As much I understand OpenPyXl is just reading the cached formula values that Excel provides. Everytime Excel is opened it does the dirty job (formula evaluating) for OpenPyXl. 

- https://stackoverflow.com/questions/36116162/python-openpyxl-data-only-true-returning-none
- https://stackoverflow.com/questions/53271690/openpyxl-how-to-read-formula-result-after-editing-input-data-on-the-sheet-data

STU

**Comment by stu0408** [comment]
Short tests showed that OpenXLSX is reading the cached data from Excel already.
If in a cell e.g. following is defined ="(2+3)*3" then returned value will be 15 and not a string that represents the formula.

Therefore I will close this issue. It works as expected.

STU
