### ISSUE TITLE
XLSheet.hpp(211,19): error C2059: syntax error: 'template'

### ISSUE THREAD

**Issue by dilipvpn** [troldal/OpenXLSX#118]
XLQuery query(XLQueryType::QuerySheetIndex);
            query.template setParam("sheetID", relationshipID()); // This line is the issue
            return uint16_t(std::stoi(parentDoc().execQuery(query).template result<std::string>()));

This error is coming while Compiling with VS 2019

**Comment by CEXT-Dan** [comment]
I had the same issue, I changed mine locally to  "query.setParam"

**Comment by florianAnt** [comment]
I have removed the keyword template.
I think this makes the call syntactically correct.

XLQuery query(XLQueryType::QuerySheetIndex);
        query.setParam("sheetID", relationshipID()); // This line is the issue
        return uint16_t(std::stoi(parentDoc().execQuery(query).result<std::string>()));

**Comment by mauzil** [comment]
Me too have the same problem with VS2019.
But which c++ standard we need to compile without errors and without remote ".template"?

**Comment by xerox51** [comment]
I have meet the problem too. 
I found a mistake in  XLRowData.h header file.
you should include <iterator> header file in this file.
After that use c++17 standard will work properly.

**Comment by troldal** [comment]
This error is due to differences between MSVC and GCC/Clang. It has been fixed now and merged into the master branch. I will create a new release later.
