### ISSUE TITLE
How to check if file actually opened?

### ISSUE THREAD

**Issue by praudmur** [troldal/OpenXLSX#119]
Hello,  troldal!
I'd like to check if file actually was opened by OpenXLS after "XLDocument::open" function i.e. the file is a valid Excel file. Is there a way to do that? I can only think of getting a sheet count at the moment. It'd be gread if XLDocument::open" returned false\true depending on result.

**Comment by troldal** [comment]
Hi @praudmur 

Sorry for the late reply.

It is actually already possible as an XLDocument object can be casted to bool, so you can do something like this:    

```cpp
XLDocument doc;
if (doc)
        cout << "Document is open!" << std::endl;
    else
        cout << "Document is NOT open!" << endl;
```

However, to make things a bit more explicit, I have added a member function called isOpen(). It does exactly the same, but it may be more clear what's going on:

```cpp
XLDocument doc;
if (doc.isOpen())
        cout << "Document is open!" << std::endl;
    else
        cout << "Document is NOT open!" << endl;
```

This update has been merged into the master branch. I will create a new release shortly.
