### ISSUE TITLE
Issue in building OpenXLSX using CMake

### ISSUE THREAD

**Issue by Oussama-Kajjoune** [troldal/OpenXLSX#121]
Dear Kenneth,

Thank you for helping us by creating this important library.

I tried to follow your tutorial in YouTube using CMake, however, I found a difficulty in this step:
![image](https://user-images.githubusercontent.com/83629674/144207938-0a6603af-94fc-480b-9201-c8288fd75235.png)

As you can see, I don't have "BUILD_OBJECT_LIB" in my CMake:
![image](https://user-images.githubusercontent.com/83629674/144208202-fa36426f-3512-41e8-9b82-5aae67d4b668.png)

After generating the folder using CMake, there is no "library" folder within "Build" folder.

Thank you for you support and time.

Regards,
Oussama

**Comment by ofenloch** [comment]
On my machines (Debian and Ubuntu) the binaries are in directory build/output/

**Comment by aral-matrix** [comment]
As @ofenloch  said, the library / Demo binaries end up in the ```output``` folder, not in a ```library``` folder. Closing this now.
