### ISSUE TITLE
XLCell object has not been properly initiated

### ISSUE THREAD

**Issue by shuaibozhang** [troldal/OpenXLSX#122]
tag 0.3.2
`wksCopy.cell(1, 13).value() = 12; wksCopy.cell(1, 12).value() = 11;` 

assert "XLCell object has not been properly initiated"

must change order 

`wksCopy.cell(1, 12).value() = 12;wksCopy.cell(1, 13).value() = 11;`

**Comment by troldal** [comment]
Hi @shuaibozhang 

Sorry for the late reply.

I'm not sure what is the problem. There is practically no difference in the two codelines above. Also, I don't get a failed assertion error. Please clarify.

**Comment by aral-matrix** [comment]
Due to no feedback from originator, and the related (#226) issue likely being resolved, I am marking this issue as ready for close & will close in a few days.

**Comment by aral-matrix** [comment]
closing as resolved, since there is no contradicting feedback from originator
