### ISSUE TITLE
Cell merge and Image processing

### ISSUE THREAD

**Issue by iryna7** [troldal/OpenXLSX#126]
Hi, Does it support cell merge and image processing, i mean image insert on the cell ? please let me know.

hansoo

**Comment by troldal** [comment]
Hi @iryna7 

Sorry for the late reply. 

To answer your question, cell merge and insertion of images is unfortunately not possible. OpenXLSX is mostly for data extraction, not so much for formatting. Cell merge may come later, but insertion of images is not on the todo list right now.
