### ISSUE TITLE
call worksheetNames or sheetNames crash

### ISSUE THREAD

**Issue by chinagzcp** [troldal/OpenXLSX#128]
I used it in Unreal Engine, and when I called these two methods, it caused a crash, this is easy to reproduce.

**Comment by CEXT-Dan** [comment]
Hi, 
I use worksheetNames with no issue, maybe you can post a sample xlsx file so I can test on my setup?

**Comment by chinagzcp** [comment]
I created a default Excel and sheet through Excel 2016 without any data, and then I used it in Unreal Engine. [abc.xlsx](https://github.com/troldal/OpenXLSX/files/7811549/abc.xlsx)
![image](https://user-images.githubusercontent.com/13399635/148148562-2231886e-3777-4122-8a02-2baaa65ec3f6.png)
![image](https://user-images.githubusercontent.com/13399635/148148736-6c8928af-4b4a-418d-81ef-16a9b489f4a6.png)

**Comment by CEXT-Dan** [comment]
This works for me.

`
int main()
{
    std::filesystem::path       path = "e:\\abc.xlsx";
    std::unique_ptr<XLDocument> pDoc(new XLDocument(path.u8string()));
    std::unique_ptr<XLWorkbook> pBook(new XLWorkbook(pDoc->workbook()));
    for (auto name : pBook->worksheetNames())
        cout << name << '\n';
    return 0;
}
`

My guess is your document is being closed inadvertently

**Comment by troldal** [comment]
Hi @chinagzcp 

Glad you mad it work. Just remember that when the XLDocument object is destroyed, any references to the embedded XLWorkbook object will be invalidated.
