### ISSUE TITLE
[Feature Request] Open Document Sheet

### ISSUE THREAD

**Issue by Yaksinikos** [troldal/OpenXLSX#131]
Feature request for LibreOffice Calc's .ods (openDocumentSheet) format.

**Comment by troldal** [comment]
Hi @Yaksinikos 

I'm afraid that's not possible. The internal structure of .ods files are completely different from Excel files, so not much of the OpenXLSX source code can be re-used. And honestly, the number of people using .ods files is quite small compared to the number of Excel users, so there is not much benefit in it.
