### ISSUE TITLE
Running Demo3.exe and Demo4.exe throws Exception: terminate called after throwing an instance of 'std::bad_any_cast'

### ISSUE THREAD

**Issue by sirius-william** [troldal/OpenXLSX#132]
After compile, I run the demos that provided in EXAMPLE.
When running Demo3.exe and Demo4.exe, they all throw following exception: terminate called after throwing an instance of 'std::bad_any_cast'.

My Environment:
Windows 10
make: 4.2.1
gcc: 8.1.0
cmake:3.22.0-rc2
generator: CodeBlocks - MinGW Makefiles

Compiled as SHARED library.

Demo3.exe output the following:

`
********************************************************************************
DEMO PROGRAM #03: Sheet Handling
********************************************************************************

Sheets in workbook:
1 : Sheet1

Sheets in workbook:
1 : Sheet1
2 : Sheet2
3 : Sheet3
printWorkbook(wbk); end
Sheet1 active: true
Sheet2 active: false
Sheet3 active: false
Sheet1 active: true
Sheet2 active: false
Sheet3 active: false

Sheets in workbook:
1 : Sheet1
2 : Sheet2
3 : Sheet3
4 : Sheet4
5 : Sheet5
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
`

Demo4.exe output the following:

`
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
`

I don't know Why.

**Comment by aral-matrix** [comment]
I would hope that this issue is superseded by code updates and no longer occurs. If it does, please raise a new issue. Closing now to get some order into the open issues :)
