### ISSUE TITLE
Invalid float values  and more generally errors are not properly handled

### ISSUE THREAD

**Issue by reder2000** [troldal/OpenXLSX#146]
Writing float values that are either infinite or NaNs don't work correctly, since they are directly forwarded to pugixml.
As a result, Excel can't open the file.

I'm pushing a PR to resolve that
<img width="599" alt="Screenshot 2022-06-30 182643" src="https://user-images.githubusercontent.com/15661194/176729325-66d0a2ee-996f-4666-a76b-f0e80f88a5fa.png">
.

**Comment by troldal** [comment]
Hi @reder2000 

That's a really good point. Thanks for letting me know about this, and for providing a pull request  for it.

**Comment by reder2000** [comment]
It may slow down the thing a little bit, but if you think that a legitimate Excel file with #NUM! should be read and written back by openxlsx it seems necessary.
It was a blocker for was I was doing so I needed to sort it out quickly ! Happy to help.
