### ISSUE TITLE
Dates are not properly displayed when opening xlsx file in Excel

### ISSUE THREAD

**Issue by reder2000** [troldal/OpenXLSX#148]
It is quite annoying : dates are displayed as raw floats.

**Comment by aral-matrix** [comment]
This is no longer an issue. Using XLStyles, you can now use XLCell::setCellFormat to set a format to which you previously assigned a "number format", which can have a date formatting string.
Please refer to Demo10 for general guidance on how to use XLStyles, and then to the XLStyles ```setNumberFormatId``` functions and the ```XLNumberFormat::setFormatCode``` function to (hopefully) understand how to set a correct date formatting.

My apologies but while implementing all these, documentation took a second row seat (i.e. is not currently very extensive on the topic).
