### ISSUE TITLE
Avoid Boost.Nowide by using std::filesystem::path?

### ISSUE THREAD

**Issue by peter-jansson** [troldal/OpenXLSX#152]
If C++ 17 is ok, maybe Boost.Nowide can be avoided if [std::filesystem::path](https://en.cppreference.com/w/cpp/filesystem/path) can be used to read/write files with non-ascii names, e.g. on Windows? I believe std::filesystem::path::value_type is wchar_t on Windows.

**Comment by ofenloch** [comment]
I like the idea. I already use std::filesystem in branches.
