### ISSUE TITLE
Is is possible to access the underlying XMLDocument from XLDocument or Workbook?

### ISSUE THREAD

**Issue by shen2014** [troldal/OpenXLSX#155]
@troldal , could you please help me understand if it is possible to access the underlying xml file from  OpenXLSX::XLDocument or  OpenXLSX::Workbook? 

I am currently working with some legacy C++ code with dependency on OpenXLSX.  it tries to read Excel Ranges  via workbook().xmlDocument().  but in the latest version 0.4.x,   xlmDocument() is a projected member  of XLXmlFile and becomes not accessible. 

Many thanks!

                OpenXLSX::XLDocument doc;
		std::string formula;
		std::string rangeName;
		
		for (auto& definedName : doc.workbook().xmlDocument().document_element().child("definedNames").children()) {
			std::string formula_left;
			std::string formula_right;
			rangeName = definedName.attribute("name").value();
			formula = definedName.text().get();
			split_range(formula, formula_left, formula_right);
			range_names[rangeName] = make_pair(formula_left, formula_right);
		}

**Comment by aral-matrix** [comment]
XLWorkbook is derived from XLXmlFile. In there, among the protected member functions, is 
`
        XMLDocument& xmlDocument();
`
if you that that line to
`
public: // make xmlDocument publicly available
        XMLDocument& xmlDocument();
protected: // re-establish protection for the entries below
`
you could use that function to access the xmlDocument from anywhere in your code.

**Comment by aral-matrix** [comment]
Closing this as answered.
