### ISSUE TITLE
Add spanning support

### ISSUE THREAD

**Issue by ReBeLTheProgrammer** [troldal/OpenXLSX#159]
Hi!

Is it possible to add support for cell spanning? Excel does support this and this is a widely used thing, please, consider adding support for this in further releases.

Thanks you!

**Comment by aral-matrix** [comment]
Sorry for the late response, but did you mean the functionality to merge cells? That is in now, please refer to ```XLSheet.hpp XLWorksheet::merges, ::mergeCells, ::unmergeCells``` and to ```XLMergeCells.hpp```

Closing this assuming that is what you meant.
