### ISSUE TITLE
Example in README

### ISSUE THREAD

**Issue by VernadskyDanya** [troldal/OpenXLSX#167]
Hello, probably, it's better to add `doc.close();` command in code snipped in readme

**Comment by LucasChollet** [comment]
Why would you want to do so if `RAII` takes care of calling it for you?

**Comment by VernadskyDanya** [comment]
I am not sure that I understood what you meant, but for my c++ program it was critical, because I couldn't change excel without closing program

**Comment by LucasChollet** [comment]
As `close()` is automatically called by the destructor, adding a manual call to the method is redundant and probably not wanted.

I'm not very familiar with Qt and it also depends on how you designed your app, but you should probably have a look to `XLDocument::save()`.

**Comment by VernadskyDanya** [comment]
Got it. Thank you!
