### ISSUE TITLE
How to know if save action succeeded?

### ISSUE THREAD

**Issue by Codes-Breaker** [troldal/OpenXLSX#168]
I tried to use saveas to save file and it runs without any exception even save failed. Any idea how to know ?

**Comment by aral-matrix** [comment]
In my development branch, a failure to save will throw an exception. This change will hopefully make it here soon.

**Comment by aral-matrix** [comment]
And the change is now in the main repository: So if Save / SaveAs does not throw, it succeeded. If it fails, you will get an ```XLException``` or ```Zippy::ZipRuntimeError```
