### ISSUE TITLE
GetNewRelsID crash in opening XLSX file

### ISSUE THREAD

**Issue by zednik-matej** [troldal/OpenXLSX#169]
HI,

Program crash in algorithm function max_element on row with _seek_wraped().
When I try open XLSX file (with numbers in cells only and saved by LibreOffice Calc) program crash. And throw Exception out of range.
If I open xlsx file in MS Excel and save it. Program open this file correctly.
It looks like it´s problem with adding SharedStrings.xml in function GetNewRelsID in file XLRelationships.cpp.

[CrashFile.xlsx](https://github.com/troldal/OpenXLSX/files/9299672/CrashFile.xlsx)

**Comment by aral-matrix** [comment]
Issue is resolved with May 2024 Update (I tested CrashFile.xlsx and added a new worksheet, then saved the file without problems)
