### ISSUE TITLE
Crash when attempting to open a .csv/.xls file

### ISSUE THREAD

**Issue by hemasridhar24** [troldal/OpenXLSX#171]
There is a crash when attempting read .csv or .xls file. Attached is a csv file as an example.
[1.csv](https://github.com/troldal/OpenXLSX/files/9310281/1.csv)

**Comment by JerryCheng1** [comment]
is it only for xlsx?

**Comment by aral-matrix** [comment]
OpenXLSX can not open .xls files, as that is a proprietary and completely different (much more complex) format. There's a commercial library called "libxl" that I know of.
Closing this.
