### ISSUE TITLE
C4242: possible loss of data in XLWorksheet::columnCount

### ISSUE THREAD

**Issue by SpareSimian** [troldal/OpenXLSX#172]
Building with VS2022 on Win10 x64, XLSheet reports a C4242 possible loss of data trying to assign unsigned int to an int16_t. Easy fix is to change the temporary vector to also use unsigned int:
```
index a654bd0..b89da90 100644
--- a/OpenXLSX/sources/XLSheet.cpp
+++ b/OpenXLSX/sources/XLSheet.cpp
@@ -530,7 +530,7 @@ XLCellReference XLWorksheet::lastCell() const noexcept
  */
 uint16_t XLWorksheet::columnCount() const noexcept
 {
-        std::vector<int16_t> counts;
+        std::vector<unsigned int> counts;
         for (const auto& row : rows()) {
             counts.emplace_back(row.cellCount());
         }
```

**Comment by aral-matrix** [comment]
This has been fixed in recent patches: XLRow::cellCount() returns ```uint16_t``` and this data type is also used consistently by XLWorksheet for column references.
