### ISSUE TITLE
XLDocument.cpp(662,26): warning C4834

### ISSUE THREAD

**Issue by ThibaultDECO** [troldal/OpenXLSX#173]
`\OpenXLSX\sources\XLDocument.cpp(668,26): warning C4834: discarding return value of function with 'nodiscard' attribute [\OpenXLSX\build\OpenXLSX.vcxproj]`

This error is coming while compiling with VS 2022

**Comment by yoavmil** [comment]
https://github.com/troldal/OpenXLSX/pull/174

I think this repo is in deep freeze. too bad.

**Comment by zhiyangyou** [comment]
> #174
> 
> I think this repo is in deep freeze. too bad.

I checked some past issues and found that you are right. :(

**Comment by aral-matrix** [comment]
it's thawed :) Issue is fixed.
