### ISSUE TITLE
  Error opening Chinese name file

### ISSUE THREAD

**Issue by KenWBlack** [troldal/OpenXLSX#183]
If a xlsx file has a Chinese name and Chinese is an odd number, the program will crash.For example,we have c++ code like:
XLDocument doc1,doc2;
doc1.open("./中文.xlsx");//this will work well
doc2.open("./中文版.xlsx");//this will crash
---------------
I use VS2022, win10 platform

**Comment by aral-matrix** [comment]
Could you check whether this issue still persists? For all I can test (on Linux, with and without use of Boost.NoWide), I can save and open your example file names without problems.

**Comment by aral-matrix** [comment]
closing due to no further feedback from originator.
