### ISSUE TITLE
Count and uniqueCount attributes aren't updated in sharedStrings.xml

### ISSUE THREAD

**Issue by afalkenhahn** [troldal/OpenXLSX#187]
When new strings are added to the `sharedStrings.xml` database, it looks like OpenXLSX never updates the `count` and `uniqueCount` attributes in the `<sst>` tag so those often contain invalid values.

**Comment by aral-matrix** [comment]
This has been resolved by completely removing the count & uniqueCount attributes, as the format specification declares them co-dependent, but optional altogether.
