### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by j2doll** [troldal/OpenXLSX#2]
Dear @troldal, I wonder two things.

:one:  I would like to know the cmake version that applies to this project.

I failed to make makefile with cmake version 3.10. (Is 3.9 minimum requirement?)

I succeeded with cmake version 3.13.2.
- Ubuntu 18.04 (WSL)
   - Linux DESKTOP-AJ9QK8Q 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
- cmake version 3.13.2
- gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- GNU Make 4.1, Built for x86_64-pc-linux-gnu

:two: Do you know why the following make error message occurs? 

```
/github/OpenXLSX$ make
[  9%] Built target zlib
[ 18%] Built target bzip
[ 28%] Built target libzip
[ 37%] Built target libzip++
[ 47%] Built target pugi
[ 77%] Built target OpenXLSX
[ 78%] Linking CXX executable ../../install/bin/Benchmark
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `HMAC_Final'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `AES_encrypt'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `RAND_bytes'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `AES_set_encrypt_key'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `HMAC_CTX_init'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `HMAC_CTX_cleanup'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `EVP_sha1'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `HMAC_Update'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `HMAC_Init_ex'
/mnt/d/workspace/github/OpenXLSX/install/lib/libOpenXLSX.so: undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
collect2: error: ld returned 1 exit status
@examples/@benchmark/CMakeFiles/Benchmark.dir/build.make:83: recipe for target 'install/bin/Benchmark' failed
make[2]: *** [install/bin/Benchmark] Error 1
CMakeFiles/Makefile2:381: recipe for target '@examples/@benchmark/CMakeFiles/Benchmark.dir/all' failed
make[1]: *** [@examples/@benchmark/CMakeFiles/Benchmark.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Can I get information about the environment where the build succeeds?

And my native language is not English and my English is not fluent. Please, use EASY English. :-)

**Comment by troldal** [comment]
Hi @j2doll,

Thanks for informing me about these issues.

1. CMake 3.9 should be the sufficient. I do not understand why it does not work for you. I will investigate.

2. It appears to be an issue with OpenSSL. OpenSSL is not required for OpenXLSX, so I have disabled all AES functionality in libzip (a dependency of OpenXLSX). I have committed the changes to the GitHub repository. Will you try building the new version on your environment?

When you have tried the new version, please let me know if it works :-)

**Comment by j2doll** [comment]
thanks, I'll close this issue.

**Comment by j2doll** [comment]
Hi. 

Please check my environment. 

I failed to make makefile with cmake. 😭 

- cmake version 3.10.2
- Ubuntu 18.04 x64 (WSL)
   - Linux DESKTOP-SAONFJP 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
- gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- GNU Make 4.1 Built for x86_64-pc-linux-gnu

```
/github/OpenXLSX$ cmake -G "Unix Makefiles"
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at @library/@openxlsx/CMakeLists.txt:99 (target_link_directories):
  Unknown CMake command "target_link_directories".


-- Configuring incomplete, errors occurred!
See also "/mnt/c/workspace/github/OpenXLSX/CMakeFiles/CMakeOutput.log".
```

[CMakeOutput.log](https://github.com/troldal/OpenXLSX/files/2754965/CMakeOutput.log)

**Comment by j2doll** [comment]
:one: I found out cmake version and command version.
**target_link_directories** is not supported under cmake 3.12. 
It works only with version 3.13 or later.
- https://cmake.org/cmake/help/v3.13/manual/cmake-commands.7.html
- https://cmake.org/cmake/help/v3.12/manual/cmake-commands.7.html

:two: The new master builds well!
 I suggest to write bzip2-dev installation(prerequisite) to be in the README.
