### ISSUE TITLE
Compile Project

### ISSUE THREAD

**Issue by guipborges** [troldal/OpenXLSX#20]
XLCellReference.h(52): 'openxlsx_export.h' file not found

I am trying to compile Demo1.cpp into a project and I get this error.
I can't find this file in the downloaded packages.
Can you help me?
Thank you for your attention!

**Comment by troldal** [comment]
As @joelpelaez alludes to, you need to configure the project using CMake. During the configuration phase, CMake will generate the openxlsx_export.h file, based on the system setup of the computer you are using.

Please let me know if you can get it to work.
