### ISSUE TITLE
Please update a tag number

### ISSUE THREAD

**Issue by yoavmil** [troldal/OpenXLSX#207]
Please update a tag number because tag 0.3.2 doesn't compile for me, but master does.
FYI I want a tag number to integrate the library using `FetchContent_Declare`
```cmake
FetchContent_Declare(
	OpenXLSL
	GIT_REPOSITORY "https://github.com/troldal/OpenXLSX.git"
	GIT_TAG "master" <<-- not recomented
	SOURCE_SUBDIR "OpenXLSX"
)
```

**Comment by aral-matrix** [comment]
closing this as "probably superseded" - sorry for never responding, but I only starting contributing in 2024 and made a *lot* of changes. Should you run into another issue please let me know.
