### ISSUE TITLE
Can I use C++11 to integrate this project？

### ISSUE THREAD

**Issue by Eternity1987** [troldal/OpenXLSX#208]
Can I use C++11 to integrate this project？

XLCellValue.hpp:469:59: error: expected ',' or '>' in template-parameter-list
            typename std::enable_if<std::is_integral_v<T> || std::is_floating_point_v<T> || std::is_same_v<std::decay_t<T>, std::string> ||

**Comment by Robinsssson** [comment]
This library is written using the C++17 standard, you can check it in README.md. I'm sorry to tell that it can't integrate C++11. The `std::is_same_v` is since C++ 17. You can check it in follow web. [https://en.cppreference.com/w/cpp/types/is_same](url)

**Comment by aral-matrix** [comment]
Unfortunately, as @Robinsssson stated, the project needs a minimum of c++17 standard. I'll close this issue now.
