### ISSUE TITLE
How to merge cells in OpenXLSX and I can't find the related API?

### ISSUE THREAD

**Issue by CeaserZhou** [troldal/OpenXLSX#209]
How to merge cells in OpenXLSX and I can't find the related API?

**Comment by aral-matrix** [comment]
Check out [XLWorksheet::mergeCells](https://github.com/troldal/OpenXLSX/blob/master/OpenXLSX/headers/XLSheet.hpp) and the [XLMergeCells](https://github.com/troldal/OpenXLSX/blob/master/OpenXLSX/headers/XLMergeCells.hpp) class that were newly added recently.
