### ISSUE TITLE
where is openxlsx_export.h?

### ISSUE THREAD

**Issue by ZChidori** [troldal/OpenXLSX#21]
and how to use this library in my projects?

**Comment by troldal** [comment]
You need to configure the project using CMake...this will generate the openxlex_export.h file for you. Please also see this post: https://github.com/troldal/OpenXLSX/issues/20

**Comment by ZChidori** [comment]
> You need to configure the project using CMake...this will generate the openxlex_export.h file for you. Please also see this post: #20
I got it,thanks!
