### ISSUE TITLE
can't build lib (windows 10)

### ISSUE THREAD

**Issue by girderi** [troldal/OpenXLSX#211]
Hello. I followed the steps ...

mkdir build
cd build
cmake ..
cmake --build . --target OpenXLSX --config Release
cmake --install .

but I don't see the created .lib or .dll files. I wanted to attach them to visual studio project later. Where to look for files .lib / .dll created by cygwin?

**Comment by girderi** [comment]
I found another library that works.

**Comment by rmmales** [comment]
> I found another library that works.

For girderi: can you advise as to the library you found please?
