### ISSUE TITLE
load different document in different thread

### ISSUE THREAD

**Issue by iamtangxin** [troldal/OpenXLSX#219]
hi there, i have many xlsx files to read, so i load different document in different thread, each thread has a OpenXLSX::XLDocument object, and got the exception "bad allocation", i was confused, is that expected?
OpenXLSX branch: master
Env: VS2019 WIN32
here is my code:
```
auto doc = std::make_unique<OpenXLSX::XLDocument>();
try
{
    doc->open(path);
}
catch (std::exception& e)
{
    LogError() << "open excel(" << path << ") failed: " << e.what(); // catch exception: bad allocation
    return -1;
}
```

**Comment by aral-matrix** [comment]
Unfortunately, OpenXLSX is not thread-safe - please check out this comment from @troldal :
https://github.com/troldal/OpenXLSX/issues/32

**Comment by aral-matrix** [comment]
closing this as "wontfix" for now, as there are currently no plans for it - but maybe one day... :)
