### ISSUE TITLE
Open Demo03.xlsx with Excel2019, it prompts file needs to be recovered

### ISSUE THREAD

**Issue by clerktz** [troldal/OpenXLSX#220]
When opening the "Demo3.xlsx" file with Excel 2019, Excel prompts.
![Excel2019Prompt](https://github.com/troldal/OpenXLSX/assets/29378214/888faaa0-7805-444d-aec8-81dac9abc01f)
This is exactly the same as the previous feedback from  [bytehammer2](https://github.com/bytehammer2) ([Issue #105](https://github.com/troldal/OpenXLSX/issues/105)). 
After clicking "Yes", the file is repaired and can be opened normally.
After carefully comparing the repaired xml file changes, I finally determined that some of the element in _docProps/app.xml_ was incorrect, which caused the Excel repair prompt.

Here is the content of the "_docProps/app.xml_" file extracted from the Excel file before the recovery, you can see that the value of the _**vt:i4**_ element in **_HeadingPairs_** node is **1**.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
   <Application>Microsoft Macintosh Excel</Application>
   <DocSecurity>0</DocSecurity>
   <ScaleCrop>false</ScaleCrop>
   <HeadingPairs>
      <vt:vector size="2" baseType="variant">
         <vt:variant>
            <vt:lpstr>Worksheets</vt:lpstr>
         </vt:variant>
         <vt:variant>
            <vt:i4>1</vt:i4>
         </vt:variant>
      </vt:vector>
   </HeadingPairs>
   <TitlesOfParts>
      <vt:vector size="4" baseType="lpstr">
         <vt:lpstr>Sheet2</vt:lpstr>
         <vt:lpstr>Sheet3</vt:lpstr>
         <vt:lpstr>Sheet4</vt:lpstr>
         <vt:lpstr>Sheet5</vt:lpstr>
      </vt:vector>
   </TitlesOfParts>
   <Company />
   <LinksUpToDate>false</LinksUpToDate>
   <SharedDoc>false</SharedDoc>
   <HyperlinksChanged>false</HyperlinksChanged>
   <AppVersion>16.0300</AppVersion>
</Properties>
```
However, in the "_docProps/app.xml_" file extracted from the repaired Excel file, we can see that the value of the **_vt:i4_** element of the **_HeadingPairs_** node is **4**.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
   <Application>Microsoft Macintosh Excel</Application>
   <DocSecurity>0</DocSecurity>
   <ScaleCrop>false</ScaleCrop>
   <HeadingPairs>
      <vt:vector size="2" baseType="variant">
         <vt:variant>
            <vt:lpstr>Worksheets</vt:lpstr>
         </vt:variant>
         <vt:variant>
            <vt:i4>4</vt:i4>
         </vt:variant>
      </vt:vector>
   </HeadingPairs>
   <TitlesOfParts>
      <vt:vector size="4" baseType="lpstr">
         <vt:lpstr>Sheet2</vt:lpstr>
         <vt:lpstr>Sheet3</vt:lpstr>
         <vt:lpstr>Sheet4</vt:lpstr>
         <vt:lpstr>Sheet5</vt:lpstr>
      </vt:vector>
   </TitlesOfParts>
   <Company />
   <LinksUpToDate>false</LinksUpToDate>
   <SharedDoc>false</SharedDoc>
   <HyperlinksChanged>false</HyperlinksChanged>
   <AppVersion>16.0300</AppVersion>
</Properties>
```
So it can be inferred that the value of **_vt:i4_** of **_HeadingPairs_** node should be same with the sheets count.

Apply the following patch code to the _addSheetName_/_deleteSheetName_/appendSheetName/_prependSheetName_/_insertSheetName_ functions in _XLProperties.cpp_. The value of _**vt:i4**_ element in **_HeadingPairs_** will be equal to the sheetCount and then this bug is fixed.
```cpp
void XLAppProperties::appendSheetName(const std::string& sheetName)
{
    if (!m_xmlData) return;
    auto theNode = sheetNames(xmlDocument().document_element()).append_child("vt:lpstr");
    theNode.text().set(sheetName.c_str());
    int sheetCnt = sheetCount(xmlDocument().document_element()).as_uint();
    sheetCnt++;
    sheetCount(xmlDocument().document_element()).set_value(sheetCnt);
    headingPairsCounts(xmlDocument().document_element()).first_child().text().set(sheetCnt);
}
```

**Comment by aral-matrix** [comment]
Interesting - this is still saved as `<vt:i4>1</vt:i4>` - maybe I should have read the issue list a few months ago :)
I'll try to find the specification of this field & whether it is indeed intended to hold the count of worksheets (which seems logical).

**Comment by aral-matrix** [comment]
Okay, development branch is merged into main - this should be resolved.
