### ISSUE TITLE
怎样合并单元格

### ISSUE THREAD

**Issue by WilliamQf-AI** [troldal/OpenXLSX#223]
怎样合并单元格

**Comment by Robinsssson** [comment]
这是一个使用formula的方法，即使用Windows Excel内部函数的方法。可以解决您的问题，如果有更近一步的需求，可以add-feature，似乎本项目没有相关的Api，希望能够帮到你。
[https://support.microsoft.com/zh-cn/office/%E5%B0%86%E4%B8%A4%E4%B8%AA%E6%88%96%E6%9B%B4%E5%A4%9A%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E7%9A%84%E6%96%87%E6%9C%AC%E5%90%88%E5%B9%B6%E5%88%B0%E4%B8%80%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC-81ba0946-ce78-42ed-b3c3-21340eb164a6#:~:text=%E4%BD%BF%E7%94%A8%20%26%20%E5%8F%B7%E7%BB%84%E5%90%88%E6%95%B0%E6%8D%AE%201%20%E9%80%89%E6%8B%A9%E8%A6%81%E6%94%BE%E7%BD%AE%E5%90%88%E5%B9%B6%E5%90%8E%E6%95%B0%E6%8D%AE%E7%9A%84%E5%8D%95%E5%85%83%E6%A0%BC%E3%80%82%202%20%E9%94%AE%E5%85%A5%E2%80%9C%3D%E2%80%9D%EF%BC%8C%E7%84%B6%E5%90%8E%E9%80%89%E6%8B%A9%E8%A6%81%E5%90%88%E5%B9%B6%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E3%80%82%203,%E2%80%9D%EF%BC%8C%E7%84%B6%E5%90%8E%E4%BD%BF%E7%94%A8%E5%BC%95%E5%8F%B7%EF%BC%88%E4%B8%AD%E9%97%B4%E6%9C%89%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC%EF%BC%89%E3%80%82%204%20%E9%80%89%E6%8B%A9%E8%A6%81%E5%90%88%E5%B9%B6%E7%9A%84%E4%B8%8B%E4%B8%80%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8C%89%20Enter%E3%80%82%20%E7%A4%BA%E4%BE%8B%E5%85%AC%E5%BC%8F%E5%8F%AF%E8%83%BD%E6%98%AF%E2%80%9C%20%3DA2%26%22%20%22%26B2%20%E2%80%9D%E3%80%82](url)

**Comment by aral-matrix** [comment]
I have implemented cell merging functionality in my development branch & hope that it will come here to the repo eventually. If possible, please keep the posts in English (I used google translate to understand at least the title).

我已经在开发分支中实现了单元格合并功能，希望它最终能出现在存储库中。如果可能的话，请保留英文帖子（我使用了谷歌翻译来理解至少标题）。

**Comment by aral-matrix** [comment]
Functionality is implemented in the main branch. Closing this.
