### ISSUE TITLE
Random Rows Random Columns Write Crash XLCell object has not been properly initiated

### ISSUE THREAD

**Issue by ClearSeve** [troldal/OpenXLSX#226]
```cpp
#include <OpenXLSX.hpp>
#include <iostream>
#include <cmath>
#include <time.h>

using namespace std;
using namespace OpenXLSX;

int main()
{
    XLDocument doc;
    doc.create("./Demo01.xlsx");
    auto wks = doc.workbook().worksheet("Sheet1");
    for (size_t i = 0; i < 1000; i++) {
        wks.cell(rand() % 100 + 1, rand() % 100 + 1).value() = "test";
    }
    doc.save();
    doc.close(); 
    return 0;
}
```
error msg: `XLCell object has not been properly initiated`
![image](https://github.com/troldal/OpenXLSX/assets/26833671/2b5daee0-71ee-4c73-9731-f4c4347f39ba)
Windows11、Visual Studio 2022、OpenXLSX master branch(commit b80da42)

Same issue:
https://github.com/troldal/OpenXLSX/issues/122

**Comment by aral-matrix** [comment]
I modified your example to be more demanding and can not reproduce the issue on Linux / g++. Also, the checks that threw an exception in your case have become obsolete and removed.
Can you check with the current version here whether the below code (or your original one) work now?

I will mark this issue as "ready for closure" and close it in a few days.

```
#include <OpenXLSX.hpp>
#include <iostream>
#include <cmath>
#include <time.h>

using namespace std;
using namespace OpenXLSX;

int main()
{
    XLDocument doc;
    doc.create("./Demo01.xlsx");
    auto wks = doc.workbook().worksheet("Sheet1");
    for (size_t i = 0; i < 100000; i++) {
        wks.cell(rand() % 10000 + 1, rand() % 5000 + 1).value() = i;
    }
    doc.save();
    doc.close(); 
    return 0;
}
```

**Comment by aral-matrix** [comment]
closing as there's no further feedback from originator and the issue appears appears to no longer occur.
