### ISSUE TITLE
Is there any API to set a cell's color

### ISSUE THREAD

**Issue by qyyyqlm** [troldal/OpenXLSX#227]
Is there any API to set a cell's color

**Comment by aral-matrix** [comment]
Full styles support done this week. I am still going to refine it a bit more to be in line with https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_SpreadsheetML_topic_ID0EBC63.html and then I will submit it to @troldal for approval & inclusion into the repository.

The usage is a bit "cumbersome" to accommodate the way in which XLSX stores formats:

`
	// get the relevant style objects for easy access
	XLCellFormats & cellFormats = doc.styles().cellFormats();
	XLFonts & fonts = doc.styles().fonts();
	XLFills & fills = doc.styles().fills();

	XLCellRange myCellRange = wks.range("B20:P25");           // create a new range for formatting
	myCellRange = "TEST COLORS";                              // write some values to the cells so we can see format changes
	XLStyleIndex baseFormat = wks.cell("B20").cellFormat();   // determine the style used in B20
	XLStyleIndex newCellStyle = cellFormats.create( cellFormats[ baseFormat ] ); // create a new style based on the style in B20
	XLStyleIndex newFontStyle = fonts.create(fonts[ cellFormats[ baseFormat ].fontIndex() ]); // create a new font style based on the used font
	XLStyleIndex newFillStyle = fills.create(fills[ cellFormats[ baseFormat ].fillIndex() ]); // create a new fill style based on the used fill

	fonts[ newFontStyle ].setFontColor( XLColor( "ff00ff00" ) );          // green
	cellFormats[ newCellStyle ].setFontIndex( newFontStyle );

	fills[ newFillStyle ].setPatternType    ( XLFillPatternSolid );       // "solid"
	fills[ newFillStyle ].setColor          ( XLColor( "ffffff00" ) );    // yellow
	// fills[ newFillStyle ].setBackgroundColor( XLColor( "ff0000ff" ) );    // blue, setBackgroundColor only makes sense with gradient fills
	cellFormats[ newCellStyle ].setFillIndex( newFillStyle );

	myCellRange.setFormat( newCellStyle ); // assign the new format to the full range of cells
`

**Comment by aral-matrix** [comment]
Functionality available in the main branch now. Closing this as resolved.
