### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by gleb-kun** [troldal/OpenXLSX#233]
Hello! When I try to open an existing file:

```
terminate called after throwing an instance of 'Zippy::ZipRuntimeError'
  what():  failed finding central directory
Aborted (core dumped)
```

Code:
```
    OpenXLSX::XLDocument doc;
    doc.open("input.xlsx");
```

This happens with any input files, including completely new ones.

**Comment by aral-matrix** [comment]
@gleb-kun could you check whether this is still an issue with the current version?

**Comment by wrxhardworking** [comment]
hello ,so did you hava solved?

**Comment by aral-matrix** [comment]
How should I know? OP isn't responding. 
@wrxhardworking :
Do you have the same problem? If so, could you submit an example document?

**Comment by aral-matrix** [comment]
Closing due to lack of feedback from originator. @gleb-kun : Please open a new issue with a detailed problem description should this still be troubling you.
