### ISSUE TITLE
Any way to force re-calculation of formulas?

### ISSUE THREAD

**Issue by cbrngrz** [troldal/OpenXLSX#237]
Having an issue where formulas are not being automatically recalculated on some versions of Excel and LibreOffice. I cannot guarantee that clients will be using the correct version of an app and was hoping to get OpenXLSX to recalculate formulas that are saved from a template XLSX file.

I am using the library to open an existing XLSX Template file that has a number of formulas saved, reading data from different sheets. I use the library to write data to some sheets and save the output. When a client opens the resulting file, the data is not recalculated.

I've tried reapplying the formula after writing the sheets but that does not solve the issue. Is there a way I can get this done with the library?

**Comment by cbrngrz** [comment]
Looks like this can be resolved by assigning an empty string value to the formula cells. Closing the issue.

**Comment by fauder** [comment]
If anyone reading this is encountering this issue, check this PR: https://github.com/troldal/OpenXLSX/pull/80
