### ISSUE TITLE
error: '::_wfopen' has not been declared

### ISSUE THREAD

**Issue by eunwoo** [troldal/OpenXLSX#238]
While I am building using CMake, I got this error.
This is the full message.
I used MinGW(64) in Windows 11.

[  1%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCell.cpp.obj
[  3%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCellIterator.cpp.obj
[  4%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCellRange.cpp.obj
[  6%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCellReference.cpp.obj
[  7%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCellValue.cpp.obj
[  9%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLColor.cpp.obj
[ 10%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLColumn.cpp.obj
[ 12%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLContentTypes.cpp.obj
In file included from C:/Study/OpenXLSX/OpenXLSX/headers/XLDocument.hpp:62,
                 from C:\Study\OpenXLSX\OpenXLSX\sources\XLContentTypes.cpp:52:
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:223:53: warning: inline function 'virtual std::unique_ptr<OpenXLSX::IZipArchive::Concept> OpenXLSX::IZipArchive::Concept::clone() const' used but never defined
  223 |             inline virtual std::unique_ptr<Concept> clone() const = 0;
      |                                                     ^~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:225:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::isValid() const' used but never defined
  225 |             inline virtual bool isValid() const = 0;
      |                                 ^~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:227:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::isOpen() const' used but never defined
  227 |             inline virtual bool isOpen() const = 0;
      |                                 ^~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:229:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::open(const string&)' used but never defined
  229 |             inline virtual void open(const std::string& fileName) = 0;
      |                                 ^~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:231:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::close()' used but never defined
  231 |             inline virtual void close() = 0;
      |                                 ^~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:233:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::save(const string&)' used but never defined
  233 |             inline virtual void save (const std::string& path) = 0;
      |                                 ^~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:235:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::addEntry(const string&, const string&)' used but never defined
  235 |             inline virtual void addEntry(const std::string& name, const std::string& data) = 0;
      |                                 ^~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:237:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::deleteEntry(const string&)' used but never defined
  237 |             inline virtual void deleteEntry(const std::string& entryName) = 0;
      |                                 ^~~~~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:239:40: warning: inline function 'virtual std::string OpenXLSX::IZipArchive::Concept::getEntry(const string&)' used but never defined
  239 |             inline virtual std::string getEntry(const std::string& name) = 0;
      |                                        ^~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:241:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::hasEntry(const string&)' used but never defined
  241 |             inline virtual bool hasEntry(const std::string& entryName) = 0;
      |                                 ^~~~~~~~
[ 13%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLDateTime.cpp.obj
[ 15%] Building CXX object OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLDocument.cpp.obj
In file included from C:/Study/OpenXLSX/OpenXLSX/external/nowide/nowide/fstream.hpp:16,
                 from C:\Study\OpenXLSX\OpenXLSX\sources\XLDocument.cpp:47:
C:/Study/OpenXLSX/OpenXLSX/external/nowide/nowide/filebuf.hpp: In member function 'nowide::basic_filebuf<char>* nowide::basic_filebuf<char>::open(const char*, std::ios_base::openmode)':
C:/Study/OpenXLSX/OpenXLSX/external/nowide/nowide/filebuf.hpp:93:25: error: '::_wfopen' has not been declared; did you mean 'fopen'?
   93 |             FILE* f = ::_wfopen(name.c_str(), smode);
      |                         ^~~~~~~
      |                         fopen
In file included from C:/Study/OpenXLSX/OpenXLSX/headers/XLDocument.hpp:62,
                 from C:\Study\OpenXLSX\OpenXLSX\sources\XLDocument.cpp:55:
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp: At global scope:
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:223:53: warning: inline function 'virtual std::unique_ptr<OpenXLSX::IZipArchive::Concept> OpenXLSX::IZipArchive::Concept::clone() const' used but never defined
  223 |             inline virtual std::unique_ptr<Concept> clone() const = 0;
      |                                                     ^~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:225:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::isValid() const' used but never defined
  225 |             inline virtual bool isValid() const = 0;
      |                                 ^~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:227:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::isOpen() const' used but never defined
  227 |             inline virtual bool isOpen() const = 0;
      |                                 ^~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:229:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::open(const string&)' used but never defined
  229 |             inline virtual void open(const std::string& fileName) = 0;
      |                                 ^~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:231:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::close()' used but never defined
  231 |             inline virtual void close() = 0;
      |                                 ^~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:233:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::save(const string&)' used but never defined
  233 |             inline virtual void save (const std::string& path) = 0;
      |                                 ^~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:235:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::addEntry(const string&, const string&)' used but never defined
  235 |             inline virtual void addEntry(const std::string& name, const std::string& data) = 0;
      |                                 ^~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:237:33: warning: inline function 'virtual void OpenXLSX::IZipArchive::Concept::deleteEntry(const string&)' used but never defined
  237 |             inline virtual void deleteEntry(const std::string& entryName) = 0;
      |                                 ^~~~~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:239:40: warning: inline function 'virtual std::string OpenXLSX::IZipArchive::Concept::getEntry(const string&)' used but never defined
  239 |             inline virtual std::string getEntry(const std::string& name) = 0;
      |                                        ^~~~~~~~
C:/Study/OpenXLSX/OpenXLSX/headers/IZipArchive.hpp:241:33: warning: inline function 'virtual bool OpenXLSX::IZipArchive::Concept::hasEntry(const string&)' used but never defined
  241 |             inline virtual bool hasEntry(const std::string& entryName) = 0;
      |                                 ^~~~~~~~
OpenXLSX\CMakeFiles\OpenXLSX.dir\build.make:210: recipe for target 'OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLDocument.cpp.obj' failed
mingw32-make.exe[2]: *** [OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLDocument.cpp.obj] Error 1
CMakeFiles\Makefile2:231: recipe for target 'OpenXLSX/CMakeFiles/OpenXLSX.dir/all' failed
mingw32-make.exe[1]: *** [OpenXLSX/CMakeFiles/OpenXLSX.dir/all] Error 2
Makefile:134: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by aral-matrix** [comment]
Closing due to lack of feedback. Please re-open if the issue reoccurs.
