### ISSUE TITLE
compile error, need to add #include <cstdint> in XLCellReference.hpp, XLColor.hpp, XLDateTime.cpp

### ISSUE THREAD

**Issue by ChendongPang** [troldal/OpenXLSX#242]
[  1%] Building CXX object OpenXLSX/OpenXLSX/CMakeFiles/OpenXLSX.dir/sources/XLCellReference.cpp.obj
In file included from C:\Users\86189\Desktop\workspace\OpenXLSX\OpenXLSX\sources\XLCellReference.cpp:54:
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:65:37: error: 'uint32_t' was not declared in this scope
   65 |     using XLCoordinates = std::pair<uint32_t, uint16_t>;
      |                                     ^~~~~~~~
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:59:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   58 | #include "OpenXLSX-Exports.hpp"
  +++ |+#include <cstdint>
   59 |
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:65:47: error: 'uint16_t' was not declared in this scope
   65 |     using XLCoordinates = std::pair<uint32_t, uint16_t>;
      |                                               ^~~~~~~~
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:65:47: note: 'uint16_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:65:55: error: template argument 1 is invalid
   65 |     using XLCoordinates = std::pair<uint32_t, uint16_t>;
      |                                                       ^
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:65:55: error: template argument 2 is invalid
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:97:33: error: expected ')' before 'row'
   97 |         XLCellReference(uint32_t row, uint16_t column);
      |                        ~        ^~~~
      |                                 )
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:104:33: error: expected ')' before 'row'
  104 |         XLCellReference(uint32_t row, const std::string& column);
      |                        ~        ^~~~
      |                                 )
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:165:9: error: 'uint32_t' does not name a type
  165 |         uint32_t row() const;
      |         ^~~~~~~~
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:165:9: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
C:/Users/86189/Desktop/workspace/OpenXLSX/OpenXLSX/headers/XLCellReference.hpp:171:21: error: 'uint32_t' has not been declared
  171 |         void setRow(uint32_t row);

**Comment by Hans774882968** [comment]
For me, I simply followed the error message and added `#include <cstdint>` to several hpp files, such as `OpenXLSX\headers\XLCellReference.hpp` and `OpenXLSX\headers\XLDateTime.hpp`. Then everything turned out fine.

For more information, feel free to check out this project of mine, which demonstrates how to configure OpenXLSX: https://github.com/Hans774882968/cpp-xlsx-demo

**Comment by AnatoliiShablov** [comment]
Same

**Comment by aral-matrix** [comment]
This issue has been fixed in the May 2024 Update.
