### ISSUE TITLE
[OpenXLSX::XLInputError]Dont open file.xlsx.

### ISSUE THREAD

**Issue by fjcheng** [troldal/OpenXLSX#247]
[
[params.xlsx](https://github.com/troldal/OpenXLSX/files/15427920/params.xlsx)
](url)

params.xlsx is created locally and then wrote to the data. An OpenXLSX::XLInputError in the XLDocument::open method which was amended on 2024-05-03, is reported,when using openxlsx to read this file.

When the params.xlsx content is copied to the excel file generated by openxlsx in an unformatted format, openxlsx can read it normally.

Now, I am not sure why this is happening, and what can I do to solve this problem?

**Comment by troldal** [comment]
Hi @fjcheng,

There was a bug in the loading of shared strings. It's been fixed now and commited to the master branch. Please give it a try.

**Comment by fjcheng** [comment]
Hi@troldal

Yes, It's working properly. Great, thanks.
