### ISSUE TITLE
The file address can only be an absolute path, but not a relative path？

### ISSUE THREAD

**Issue by xiaoyangst** [troldal/OpenXLSX#249]
My absolute path can succeed, but the relative path can't successfully create the file, that's all, is it the way it is, or something else?

**Comment by aral-matrix** [comment]
What platform are you on? Can you open a file within the local folder? I.e. does  this work for you? ```XLDocument doc("./test.xlsx"s);```

**Comment by aral-matrix** [comment]
closing as issue creator provided no further information
