### ISSUE TITLE
Issue in the amount of data saved in sheet.xml

### ISSUE THREAD

**Issue by YoannNicod** [troldal/OpenXLSX#25]
I found a second issue, which I had after saving an existing xlsx file with only one cell modified : the layout changed.

To reproduce the problem, I reduced my file to the minimum :
[good.xlsx](https://github.com/troldal/OpenXLSX/files/4012696/good.xlsx)
This is a very simple file, with A and B column always visible and a fixed number of columns.

When I execute this code :

	int main()
	{
	  XLDocument doc;

	  doc.OpenDocument("./good.xlsx");

	  auto wks = doc.Workbook().Worksheet("2019");

	  wks.Cell("K11").Value() = 77;

	  doc.SaveDocument();
	  doc.CloseDocument();

	  return 0;
	}

I obtain a file that lost the limited column number :
[bad.xlsx](https://github.com/troldal/OpenXLSX/files/4012701/bad.xlsx)

You can notice the problem when looking at the horizontal slide bar in both documents.
It also dramatically increases the file size as a consequence.
I am not sure the fact that I modify one cell has something to do with it, since I think I also had the problem without modifying anything (not sure though).

I think that the document should keep its features after being opened and modifed by the lib.

**Comment by troldal** [comment]
Hi @YoannNicod,

I'm afraid I can't re-create the issue on my machine. On my computer the 'good.xlsx' and 'bad.xlsx' are identical, except for the value in cell K11 and the increased file size. I can't see the fixed number of columns in the 'good.xlsx' file. I' using Excel on a Mac...maybe that's the reason...?

**Comment by kevinofsias** [comment]
> Hi @YoannNicod,
> 
> I'm afraid I can't re-create the issue on my machine. On my computer the 'good.xlsx' and 'bad.xlsx' are identical, except for the value in cell K11 and the increased file size. I can't see the fixed number of columns in the 'good.xlsx' file. I' using Excel on a Mac...maybe that's the reason...
> 
> Can you send a screenshot so I can see what your issue is?

I have the same problem，the bad excel size increased because it has so many empty column。
![image](https://user-images.githubusercontent.com/11285988/139537032-415f7f15-ea66-476a-8886-23277f419f31.png)
