### ISSUE TITLE
can it read and export *.xls files?

### ISSUE THREAD

**Issue by Vdeilae** [troldal/OpenXLSX#250]

**Comment by aral-matrix** [comment]
Unfortunately, no. The XLS format is highly complex and requires a very large codebase to support. The only (commercial) library I am aware of to write .xls from c++ is libxl
Unless you have a use case with a legacy file format, I recommend that you switch to .xlsx.

**Comment by nenin-sc** [comment]
There are some solutions for xls files. 
"Read" is here  https://github.com/libxls/libxls
I tried it more than 10 years ago, it did not impressed me. May be now it is better?
"Write" is here: https://sourceforge.net/projects/xlslib/files/ It is working OK (I`m using it with mingw 32b), but it is also a really old stuff. 
As it was noted by  [aral-matrix](https://github.com/aral-matrix),  "Read-Write" in one lib has only  commercial implementations.

**Comment by aral-matrix** [comment]
Interesting, @nenin-sc, I did not know about libxls yet - however:

> After several years of neglect, libxls is under new management as of the 1.5.x series. Head over to [releases](https://github.com/libxls/libxls/releases) to get the latest stable version of libxls 1.5, which fixes many security vulnerabilities found in libxls 1.4 and earlier.

How badly does one design a file format reading/writing library for it to even *be able to* have security vulnerabilities? oO

**Comment by nenin-sc** [comment]
> How badly 

It is not a big problem for the C code. Insufficient buffer length control, for example.

**Comment by aral-matrix** [comment]
> It is not a big problem for the C code. Insufficient buffer length control, for example.

Exactly ;) Anyways, this is going off-topic, and I don't want to confuse readers about OpenXLSX with talks about another project's vulnerabilities.

**Comment by aral-matrix** [comment]
closing this issue as answered.
