### ISSUE TITLE
How to set C++ 14 as the standard?

### ISSUE THREAD

**Issue by nicosafull** [troldal/OpenXLSX#257]
I see there is CMAKE_CXX_STANDARD and it's set to 17, when I set it to 14 it seems nothing happens? Ofc I need it for C++ 14

**Comment by aral-matrix** [comment]
As far as I am aware, the library is using features that are not yet supported on C++14, I am afraid :/ I'd have to check which ones, but it might be impossible to compile on C++14 functionality without some major changes.

**Comment by aral-matrix** [comment]
Yeah, just checked - the template logic that OpenXLSX relies on is only supported as of C++17 and higher.
