### ISSUE TITLE
inline string mark not removing

### ISSUE THREAD

**Issue by genyez** [troldal/OpenXLSX#271]
A separate issue from https://github.com/troldal/OpenXLSX/issues/243

In `OpenXLSX/sources/XLCellValue.cpp` function `XLCellValueProxy::setString`, around line 397 .
I think something like 
``if (m_cellNode->child("is")) m_cellNode->remove_child("is");``

should be there, to remove a Inline String mark, so that when we set a string correctly.

In addition, I found this bug back in Apr 30th. Just close it if it has been fixed, appreciate it!

**Comment by aral-matrix** [comment]
Line 427/428 in the current main release:
```
    // ===== Remove the is node (only relevant in case previous cell type was "inlineStr"). // pull request #188
    m_cellNode->remove_child("is");
```
Note: pugixml does not require a check whether a child exists, removing a non-existing child silently fails with a no-op.

Closing this as completed.
