### ISSUE TITLE
can"t open the file

### ISSUE THREAD

**Issue by wrxhardworking** [troldal/OpenXLSX#274]
`    OpenXLSX::XLDocument doc;

    doc.open("/mnt/c/Users/ISVPO1371/Desktop/Spreadsheet.xlsx");`

terminate called after throwing an instance of 'Zippy::ZipRuntimeError'
  what():  failed finding central directory

**Comment by aral-matrix** [comment]
This error originates from zippy.hpp ```mz_zip_reader_locate_header_sig``` returning false - there seems to be something wrong with your Spreadsheet.xlsx.

Could you please provide a minimal example file that triggers the error? I'll have a look at it then.

**Comment by aral-matrix** [comment]
If there's no response with further information to describe the issue, I'll close it in a few days.

**Comment by Cici-first** [comment]
I had the same problem, even the newly created xlsx file did not open.

**Comment by aral-matrix** [comment]
@Cici-first: Good morning! :) Could you be a little more specific? You got the "failed finding central directory" error? 
1) What operating system are you on?
2) What path were you trying to open?
3) Can you open the same file from a local folder or does the error also occur on doc.open("./myfile.xlsx")?

**Comment by Cici-first** [comment]
The error is:terminate called after throwing an instance of 'Zippy::ZipRuntimeError'  what():  file open failed
The computer is i7
doc.open("./1.xlsx") also failed ,and  This file is just created.

**Comment by aral-matrix** [comment]
So you are getting a *different* error. I'll close this issue then, and would ask you to open a new issue.

Please be more specific in your description.
By your reaction to my first question, I have to assume you are on Windows?

Further communication in the new issue, once you create it. I would like to keep different issues separate.
