### ISSUE TITLE
The bug fix on MacOs is missing in branch master

### ISSUE THREAD

**Issue by gengxiandada** [troldal/OpenXLSX#278]
[https://github.com/troldal/OpenXLSX/blob/master/OpenXLSX/sources/XLDateTime.cpp](url)
The bug fix on MacOs is missing and should include `"#include <string>"` in the header

**Comment by aral-matrix** [comment]
I do not understand. XLDateTime.cpp does not use std::strings anywhere? How can this be a bug? Could you be more specific / maybe post a compiler error message?

**Comment by aral-matrix** [comment]
Understood - thank you for reporting this. The actual missing include was in ```XLException.hpp``` - please have a look at commit 58950bebdcefccb45d553a8d83661d33b9e0778b - this should address the follow-up error you are seeing.

**Comment by aral-matrix** [comment]
closing as resolved (based on your thumbs up reaction ;)
