### ISSUE TITLE
 the support for Chinese paths

### ISSUE THREAD

**Issue by gengxiandada** [troldal/OpenXLSX#280]
Hello, I wonder if the library support opening files that contain Chinese paths on Windows. I know it works on MacOS and Linux, since I have tried it. For example, the file path is "./文件.xlsx".
When I run the following codes:
`std::string filePath = "./文件.xlsx";
OpenXLSX::XLDocument doc;
doc.open(filePath);`, 
the program exits with exit code 3.
I don't know if this is because the support for Chinese paths is not implemented yet(Windows), or something else?

**Comment by aral-matrix** [comment]
Support is in - on windows Boost.NoWide is used for that purpose - please make sure your files are encoded in UTF-8. This should work for you.

Let me quote @troldal  from a different issue:
> Another thing that have caused problems in the past, is the text encoding of the source files themselved. The source files MUST be in UTF-8 encoding, otherwise there will be problems. On systems with a Chinese locale, the default encoding is sometimes GB2312 instead of UTF-8; if that is the case, all the files should be re-saved in UTF-8 format.

**Comment by aral-matrix** [comment]
PS: To know that nowide is active in your build environment, you can add this code to your main program for debugging:
```
#ifdef ENABLE_NOWIDE
   std::cout << "nowide is enabled!" << std::endl;
#else
   std::cout << "nowide is not in use!" << std::endl;
#endif
```

**Comment by gengxiandada** [comment]
I found out the reason! I just did what u said to find that the ENABLE_NOWIDE was not activated in the project. Due to my stupidity the submodule did not build the nowide library and I did not link nowide::nowide in my CMakelists.txt file. Thank you for your patient help!

**Comment by aral-matrix** [comment]
I am glad I could help :) Closing this as completed then - and happy coding!
