### ISSUE TITLE
How to modify cell color when writing to xlsx   #227 test ok

### ISSUE THREAD

**Issue by Cici-first** [troldal/OpenXLSX#289]

**Comment by Cici-first** [comment]
#227 can only set cell color, but cannot be modified

**Comment by aral-matrix** [comment]
2 ways:
1) you change the existing fill style:
-> get cell format ID with ```XLCell::cellFormat()```
-> get fill index used by that format: ```XLCellFormat::fillIndex()```
-> change the color used by that fill style: ```XLFill::setColor``` / ```XLFill::setBackgroundColor```
 (you access the fills as per Demo10: ```XLFills & fills = doc.styles().fills();``` and then ```fills[ desiredFillIndex ]```

**Caution**: This will affect *all* cells using that cell format (or that fill index, which may also affect other cells)

2) you create a new style and/or a new fill style for the cell as per Demo10.

The mid-way, to only create a new fill style, is also basically per Demo10 examples, just that you assign the fill ID to the existing cell format with ```XLCellFormat::setFillIndex```

Again, **caution**: this will not affect cells using the old fill style, but it will affect those using the same cell format.

**Comment by ejar58** [comment]
Hello, this code does it

#include <OpenXLSX.hpp>
#include <external/pugixml/pugixml.hpp>

using namespace OpenXLSX;

int main(int argc, char* argv[])
{

	XLDocument doc{};
	doc.create("./test.xlsx", XLForceOverwrite);

	XLNumberFormats& numberFormats = doc.styles().numberFormats();
	XLFills& fills = doc.styles().fills();
	XLCellFormats& cellStyleFormats = doc.styles().cellStyleFormats();
	XLCellFormats& cellFormats = doc.styles().cellFormats();
	XLCellStyles& cellStyles = doc.styles().cellStyles();

	XLWorksheet wks = doc.workbook().worksheet(1);
	XLCellRange myCellRange = wks.range("A2");           // create a new range for formatting
	myCellRange = "59";
	XLStyleIndex cellFormatIndexA2 = wks.cell("A2").cellFormat();                 // get index of cell format
	XLStyleIndex newCellStyle = cellFormats.create(cellFormats[cellFormatIndexA2]); // create a new style based on the style in A2
	XLStyleIndex newFillStyle = fills.create(fills[cellFormats[cellFormatIndexA2].fillIndex()]); // create a new fill style based on the used fill

	XLColor red("77ff0000");
	fills[newFillStyle].setPatternType(XLPatternSolid);
	fills[newFillStyle].setColor(red);
	cellFormats[newCellStyle].setFillIndex(newFillStyle);
	myCellRange.setFormat(newCellStyle);

	doc.saveAs("./test.xlsx", XLForceOverwrite);
	doc.close();

	return 0;

}

**Comment by aral-matrix** [comment]
@ejar58  thank you for the detailed description / example. I was waiting for feedback from @Cici-first - but if that doesn't come eventually, I will close this as resolved.
