### ISSUE TITLE
Larger Files Support: >2GB

### ISSUE THREAD

**Issue by nyckmaia** [troldal/OpenXLSX#29]
Hi, I would like to know if I can use this library to generate larger XLSX files **larger** then 2GB.
**Is this possible?**

**Comment by troldal** [comment]
Hi @nyckmaia,

I know you asked this question a long time ago, but I have worked on a significant update of the OpenXLSX library and also done some benchmarks of the library. You can find the details here: https://github.com/troldal/OpenXLSX#file-size.

I managed to generate a file with a size of 1.4 GB, by dividing the data over four different worksheets in the same workbook. I don't see why it shouldn't be possible to generate files larger than 2 GB.
