### ISSUE TITLE
Error in zippy.hpp：: : Microsoft C++ exception: std::bad_alloc, Located at memory location 0x00EFD5C8.

### ISSUE THREAD

**Issue by Polors** [troldal/OpenXLSX#294]
![333](https://github.com/user-attachments/assets/112d14d2-1006-4b5c-a0fd-a5dcbc552f5a)
When I tried to test demo6 and demo7, I encountered the above problem. In the zippy.hpp file, line 10047 showed an error. It happened in the save stage. My compiler is: Vs2019 32-bit. The memory of my host is 32G. Is there any way to solve it?

**Comment by aral-matrix** [comment]
In the graph of your debugging environment, it shows only 2 GB of memory, with a steady increase in memory usage, eventually plateauing at the maximum. Going by this alone, I would assume that you have a memory leak in your program or environment, and the bad alloc is actually a bad allocation where the program fails to allocate memory for a trivial variable assignment.
Is it possible that you are having actual out of memory situation? Try increasing the limit for your program memory to 4GB and see if the same problem occurs, but elsewhere in the code.

**Comment by Polors** [comment]
Yes, I understand. As you said, for a 32-bit x86 program, the available space for the process under VS is 2G.

> 在您的调试环境图表中，它只显示 2 GB 的内存，内存使用量稳步增加，最终稳定在最大值。仅从这一点来看，我会假设您的程序或环境中存在内存泄漏，而错误的分配实际上是错误的分配，即程序无法为简单的变量赋值分配内存。 您是否有可能遇到实际的内存不足情况？
> 
> 编辑：确实，正如您所说，您使用的是 32 位编译器，根据定义，您的进程内存被限制为 2GB。我非常确定您存在内存泄漏（或者为程序分配了太多内存）。这看起来不像是 zippy 中的错误。
> 
> 编辑2：我刚刚看到它是 Demo6，它创建了一百万行，每行有 4 个值 - 这实际上可能需要超过 2GB 的内存，所以我很抱歉假设您可能有内存泄漏。但是，是的，在这种情况下，Demo5/Demo6/Demo7 程序不适合 32 位进程。

Yes, I understand. As you said, for a 32-bit x86 program, the available space for the process under VS is 2G.

**Comment by aral-matrix** [comment]
Closing this issue then. I don't think it's important for the "load test" Demos to work under 32 bit :)
