### ISSUE TITLE
XLStyles: Ignoring currently unsupported <dxfs/tableStyles/extLst> node

### ISSUE THREAD

**Issue by wangningyu** [troldal/OpenXLSX#296]
`ignoring currently unhandled workbook item /xl/externalLinks/externalLink1.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink2.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink3.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink4.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink5.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink6.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink7.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink8.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink9.xml

ignoring currently unhandled workbook item /xl/externalLinks/externalLink10.xml

ignoring currently unhandled workbook item /xl/drawings/drawing1.xml

ignoring currently unhandled workbook item /xl/embeddings/oleObject1.bin

ignoring currently unhandled workbook item /xl/drawings/drawing2.xml

ignoring currently unhandled workbook item /xl/drawings/drawing3.xml

XLStyles: Ignoring currently unsupported <dxfs> node

XLStyles: Ignoring currently unsupported <tableStyles> node

XLStyles: Ignoring currently unsupported <extLst> node`

it open failed with this error, how to fix them?

**Comment by aral-matrix** [comment]
Those are not errors, those are notifications to let you know that OpenXLSX does not currently modify those files or support any functions related to the.
None of those messages should cause opening of a workbook to fail.
You can disable them by invoking ```XLDocument::suppressWarnings()``` before calling ```XLDocument::open```, and you can re-enable them using ```XLDocument::showWarnings()```. The warnings are enabled by default.

**Comment by Maginor** [comment]
Is it possible to make the warnings disabled by default? This is not something that is needed by most people who use this in a library in other applications, and it is not backward compatible behavior (warnings were not printed before), so now people have to go and update their code to accommodate for this change, which is not that good.

**Comment by aral-matrix** [comment]
The initial purpose of the warnings was for myself and for others to be notified if an existing XLSX contains a note that I wasn't yet aware of. I was hoping that users would report back here - but indeed, I have not made that clear and having known "unsupported nodes" in there is missing the point.
So yes, I can disable the warnings by default - just give me a few days.

**Comment by aral-matrix** [comment]
@Maginor: Okay, I have disabled the warnings by default in the development-aral branch, which will eventually be merged into the main branch. Feel free to verify.

**Comment by Maginor** [comment]
I can verify that the warnings are no longer printed by default. Thank you!

**Comment by aral-matrix** [comment]
Here as well: I will close this issue when merging the patch into the main branch.

**Comment by aral-matrix** [comment]
Patch has been merged into the main branch. Closing issue as resolved.
