### ISSUE TITLE
Version of Mingw

### ISSUE THREAD

**Issue by maddy15791** [troldal/OpenXLSX#3]
Which version of mingw are you using? Im using gcc version 8.2.0 (MinGW.org GCC-8.2.0-3)

And i get the following error. when compiling on windows 8.1

[  0%] Building C object lib/CMakeFiles/zip.dir/zip_add.c.obj
In file included from C:\Users\M\Desktop\Ironchef_excel\OpenXLSX-master\build\@l
ibrary\libzip-prefix\src\libzip\lib\zip.h:61,
                 from C:\Users\M\Desktop\Ironchef_excel\OpenXLSX-master\build\@l
ibrary\libzip-prefix\src\libzip\lib\zipint.h:53,
                 from C:\Users\M\Desktop\Ironchef_excel\OpenXLSX-master\build\@l
ibrary\libzip-prefix\src\libzip\lib\zip_add.c:36:
c:\mingw\include\stdio.h:345:12: **error**: expected '=', ',', ';', 'asm' or '__attr
ibute__' before '__mingw__snprintf'
 extern int **__mingw_stdio_redirect__**(snprintf)(char*, size_t, const char*, ...);

            ^~~~~~~~~~~~~~~~~~~~~~~~
lib\CMakeFiles\zip.dir\build.make:62: recipe for target 'lib/CMakeFiles/zip.dir/
zip_add.c.obj' failed

**Comment by maddy15791** [comment]
Solved temporarily by hacking c:\mingw\include\stdio.h (commented line 345)
But i dont think thats the right fix

**Comment by troldal** [comment]
I’m working on MacOS, using LLVM/Clang 7.0.1 and GCC 8.2.0

My Windows machine is Windows 10 with MinGW GCC 8.2.0.

I’m on vacation this week and don’t have access to my windows machine, so I can’t try it out myself.

From what you sent, the error is related to the libzip dependency (downloaded automatically by the CMake script), so not part of OpenXLSX itself.
