### ISSUE TITLE
Load XLSX File question

### ISSUE THREAD

**Issue by nyckmaia** [troldal/OpenXLSX#30]
Let's suppose that I have a big XLSX file (like 50GB of data in a single file), but the data are splited in **multiples Excel tabs.**

So, I would like to load just a single data **located in a specific Excel tab** using the OpenXLSX library.

Now, **I would like to know:**
Will the OpenXLSX library **load fisrt the entire 50GB in memory**, and than after return to me the specific data that I need?
Or is there a way to **load just the data in the specific Excel tab, without load any other file data?**

**Comment by troldal** [comment]
Hi @nyckmaia,

OpenXLSX loads each sheet lazily. What that means is that when you open an Excel workbook, only a few metadata objects are loaded into memory. Only when you request a specific worksheet in a workbook is the sheet data loaded into memory.

That being said, 50 GB does sound like a lot, and I've never tried using OpenXLSX with spreadsheets that big (I don't think I've ever **seen** a spreadsheet that big), and honestly, I would think that some sort of database is better suited for datasets that big.

But let me know if it works for you.
