### ISSUE TITLE
How to set a boeder? Please teach me!!!!  T_T 

### ISSUE THREAD

**Issue by txtxtxtxtxtxtx** [troldal/OpenXLSX#309]
Could you please give me a example about how to set the cells' borders? It bothered me a long time.

**Comment by aral-matrix** [comment]
Good point, I will add that to Demo10 eventually. For now, you can find some hints in the disabled code branch of Demo10, starting in line 290.

**Comment by txtxtxtxtxtxtx** [comment]
XLStyleIndex leftBorder = borders.create();
	borders[leftBorder].setOutline(true);
	borders[leftBorder].setLeft(OpenXLSX::XLLineStyleThin, OpenXLSX::XLColor("ff000000"));
	
	wks.cell("A2").setCellFormat(leftBorder); // I try to use the border, but it doesnt work, please give me some right codes.

**Comment by aral-matrix** [comment]
Just patched https://github.com/troldal/OpenXLSX/commit/c297aad5db9d2514662f4c21eef4fa77fac629fc - please be aware of the caution for resolution of #304

**Comment by txtxtxtxtxtxtx** [comment]
Thank you so much, I get it!!! You are a passionate genius!!! God will bless you all the time!!!

**Comment by aral-matrix** [comment]
Feel free to have a look at 53419c7dcc5a00865f1edeaaee424d1e0641cd71 - I improved the demo for cell borders a bit in Demo10

**Comment by aral-matrix** [comment]
Patch for Demo10 has been merged into main branch. Closing as resolved.
