### ISSUE TITLE
Is OpenXLSX thread safe

### ISSUE THREAD

**Issue by Duster12** [troldal/OpenXLSX#32]
Hello, 

If I compile OpenXLSX into a .dylib on MacOSX and use it in a multi-threaded environment does OpenXLSX support multi threading? Is it thread safe?

**Comment by troldal** [comment]
Hi @Duster12 

It’s not thread-safe, I’m afraid.

The underlying XML library is thread-safe for all reading operations. OpenXLSX could be made thread-safe for reading operations as well, but this is not the case at the moment, but maybe in the future.

For writing operations, it’s more complicated.

You can try the XLNT library (https://github.com/tfussell/xlnt). I don’t know if it’s thread-safe, but it’s worth checking out.
