### ISSUE TITLE
build problem on aix

### ISSUE THREAD

**Issue by tomasACE** [troldal/OpenXLSX#34]
Hi,
I have a problem with building source code on ibm aix unix. 
I've got there cmake version 3.14.3
gcc/g++ version 7.2.0 (the newest for ibm aix)

The building fails on the errors:
/opt/freeware/gcc7/lib/gcc/powerpc-ibm-aix7.1.0.0/7.2.0/include/c++/bits/stl_heap.h:108:3: error: template with C linkage
   template<typename _RandomAccessIterator>

Any suggestions?

Thx a lot
Tomas

**Comment by troldal** [comment]
Hi @tomasACE.

Sorry for the late reply.

I don't have access to AIX, but I tried to build under Linux using GCC 7.5 and it works fine (I can't install version 7.2; it may be possible, I just don't know how to do it.)

I would appreciate it if you could provide more information, e.g. the file/line in OpenXLSX where the error occurs.
