### ISSUE TITLE
File size is bigger if created by OpenXLSX than Saved by Excel.

### ISSUE THREAD

**Issue by error408** [troldal/OpenXLSX#40]
I create one .xlsx by OpenXLSX，and write something in it then save it. It's 160KB, and then I open it by Excel, and save it. it's 72KB. why?

**Comment by troldal** [comment]
Hi @error408 

That the file size is different from what Excel produces is to be expected. There are at least two reasons for that:

**Zip Algorithm**
Excel files are really a bunch of .xml files packed up in a zip archive. OpenXLSX uses the miniz library for zipping the .xml files; Excel uses a different library that may use a more efficient zip algorithm, resulting in a smaller file.

**Internal Datastructure**
Excel uses a few tricks to reduce the file size. For example, it uses a repository of 'shared strings', so if certain text strings are repeated throughout a workbook, only a single instance of that string is stored, which saves space.
OpenXLSX can read data like that, but can not (yet) produce shared strings. Hence .xlsx files produced with OpenXLSX will be slightly larger.

I hope that explains.
