### ISSUE TITLE
Can't read xlsm-file

### ISSUE THREAD

**Issue by And-Rik** [troldal/OpenXLSX#41]
Is xlsm format supported?
I open a document, but I get an error when calling Worksheet ("Sheet1")

Error text:
_terminate called after throwing an instance of 'std :: invalid_argument'
   what (): stoul
Process finished with exit code 134_

**Comment by And-Rik** [comment]
Is it possible to do xlsm-files support?

**Comment by troldal** [comment]
Hi @And-Rik 

I don't get an error when opening an xlsm file. Here's what I tried:

I created an .xlsm file with a simple VBA script, that shows a messagebox when opening the workbook (GitHub don't allow xlsm files to be uploaded, so please xhange the file extension to .xlsm after downloading): 
[WorkbookWithMacro.xlsx](https://github.com/troldal/OpenXLSX/files/4589105/WorkbookWithMacro.xlsx)

Then I run the following C++ code with OpenXLSX:

```cpp
#include <iostream>
#include <iomanip>
#include <OpenXLSX/OpenXLSX.h>

using namespace std;
using namespace OpenXLSX;

int main() {

    XLDocument doc;
    doc.OpenDocument("/Path/To/Spreadsheet/WorkbookWithMacro.xlsm");
    auto wks = doc.Workbook().Worksheet("Sheet1");

    wks.Cell("A1").Value() = 3.14159;
    wks.Cell("B1").Value() = 42;
    wks.Cell("C1").Value() = "  Hello OpenXLSX!  ";
    wks.Cell("D1").Value() = true;
    wks.Cell("E1").Value() = wks.Cell("C1").Value();

    auto A1 = wks.Cell("A1").Value().Get<double>();
    auto B1 = wks.Cell("B1").Value().Get<unsigned int>();
    auto C1 = wks.Cell("C1").Value().Get<std::string>();
    auto D1 = wks.Cell("D1").Value().Get<bool>();
    auto E1 = wks.Cell("E1").Value().Get<std::string>();

    auto val = wks.Cell("E1").Value();
    cout << val.Get<std::string>() << endl;

    cout << "Cell A1: " << A1 << endl;
    cout << "Cell B1: " << B1 << endl;
    cout << "Cell C1: " << C1 << endl;
    cout << "Cell D1: " << D1 << endl;
    cout << "Cell E1: " << E1 << endl;

    doc.SaveDocument();

    return 0;
}
```

This works as expected.

Can you send me the code you use, along with the .xlsm file that fails?
Also, what compiler/platform do you use? Clang/GCC/MSVC, Windows, MacOS, Linux?

**Comment by And-Rik** [comment]
Yes, that is right. 
On simple xlsm files, everything works. I had an error on only one file, which I can’t forward yet because of the privacy policy. It is surprising that when I save it again, the error does not repeat. I will analyze the file structure. 
Thanks for the answer.
