### ISSUE TITLE
Demo5: error C2059 syntax error: 'type'

### ISSUE THREAD

**Issue by christopherwoo** [troldal/OpenXLSX#44]
I built openxlsx library and demos successfully using msvc 2019. I test the library and demos using msvc 2015, it works except Demo5. Here's the detail error message:

![image](https://user-images.githubusercontent.com/5827934/82512096-a87a7a80-9b41-11ea-9d0a-1d6b45cbfa8d.png)

Help!

**Comment by christopherwoo** [comment]
And if I remove "case XLValueType::Integer" clause, it will build successfully.

**Comment by troldal** [comment]
Hi @christopherwoo,

My apologies for the late reply. I've spent a few months on an update to OpenXLSX, including the demo programs. They have been pushed to the GitHub repo today.
