### ISSUE TITLE
Return type OpenXLSX::XMLDocument is ambiguous with OpenXLSX::Impl XLDocument

### ISSUE THREAD

**Issue by CEXT-Dan** [troldal/OpenXLSX#49]
Visual studio 2019 x64 compile failed, I had to fully qualify 
OpenXLSX::XMLDocument* Impl::XLCell::XmlDocument() 
const OpenXLSX::XMLDocument* Impl::XLCell::XmlDocument() const 
OpenXLSX::XMLDocument* Impl::XLAbstractXMLFile::XmlDocument()
const OpenXLSX::XMLDocument* Impl::XLAbstractXMLFile::XmlDocument() const

**Comment by troldal** [comment]
No longer relevant, as the internal structure of OpenXLSX has been significantly modified.
