### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by mpaland** [troldal/OpenXLSX#5]
Very good work so far!

Can you please provide some more examples or documentation on how:
- to open and read a document
- read a certain sheet (given by name/index) out of the document

Would really appreciate that!

**Comment by troldal** [comment]
Hi @mpaland

I have been working on some significant changes to the library. It's still not done, but I have just merged into the master. So you can have a look for yourself.

In the @examples folder, I have added an example (Demo2) showing how to access sheets by name or index. Note that chart sheets are not yet supported.

I will add other examples in the near future.

I'm glad you like it. 
Any other comments or suggestions will be appreciated.
