### ISSUE TITLE
cell.ValueType should be expanded to handle currency, date, etc

### ISSUE THREAD

**Issue by CEXT-Dan** [troldal/OpenXLSX#50]
cell.ValueType should be expanded to handle currency, date, etc
no formatting would be necessary, I.e. should just return a double or int respectively ,but if I know a cell is a date, it can be handled.

**Comment by CEXT-Dan** [comment]
I guess this should be format, is it possible

**Comment by troldal** [comment]
Hi @CEXT-Dan,

This is an issue, yes. The problem, as you say, is that this is related to cell formatting. Dates and currency etc. is essentially just a floating point value, with some clever formatting. Unfortunately, handling formatting in Excel spreadsheets is not trivial. I may implement this at some point in the future, but it's not something I'm actively working on right now.

**Comment by CEXT-Dan** [comment]
> 
> 
> Hi @CEXT-Dan,
> 
> This is an issue, yes. The problem, as you say, is that this is related to cell formatting. Dates and currency etc. is essentially just a floating point value, with some clever formatting. Unfortunately, handling formatting in Excel spreadsheets is not trivial. I may implement this at some point in the future, but it's not something I'm actively working on right now.

Hello, 
My problem is, I have no idea if the value is supposed to be a date, also sometimes the date value is returned as an int because of the way DetermineNumberType works.

I don't need the formatting, I just need to know if it is a date so I can format it myself.  
Anyway, I've modified my local copy by adding XLCellType::Time for the "time" being. 
cheers :)

**Comment by CEXT-Dan** [comment]
Oh, Happy to share my changes, though I'm still a newbie when it comes to GIT, I still use SVN.
FYI, I wrote a free module that imports excel values into AutoCAD as a field. OpenXLSX works amazingly well  (sans the time issue)
AutoCAD has its own formatting end users can apply. 

Thanks for the great work : )

**Comment by gvollant** [comment]
> don't need the formatting, I just need to know if it is a date so I can format it myself.
> Anyway, I've modified my local copy by adding XLCellType::Time for the "time" being.
> cheers :)
I need the same thing exactly, @CEXT-Dan
