### ISSUE TITLE
About how to use this library and these download links...

### ISSUE THREAD

**Issue by Juwong** [troldal/OpenXLSX#52]
ok, i read through these close issues..
and too, i found these questions and confusions as they do.
also, i am from china.

THE QUESTIONS ARE:
1. i cmake. under ubuntu and vs2019, but cann't go through because of these download links, failed..maybe because of the great wall.
2. i try to install zippy (but aptitude search Zippy, no results; so i choose to install miniz. ) and pugixml (install sucess, pugixml.hpp is in dir: /usr/include ), but still cann't go through to make step..so, no openxlsx_export.h file, and also barks for "pugi dose not name a type.." in the step " make -j8" if i ignore the failed before this step

SUGGESTIONS:
make some lines of how to use this lib in README
maybe for these newbies as me...

**Comment by CEXT-Dan** [comment]
I used Visual studio's built-in cmake, I edited CMakeSettings.json to look like

<pre>
{
    "configurations": [
        {
            "name": "x64-Release",
            "generator": "Visual Studio 16 2019 Win64",
            "configurationType": "RelWithDebInfo",
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "",
            "ctestCommandArgs": "",
            "inheritEnvironments": [ "msvc_x64_x64" ],
            "variables": [],
            "cmakeToolchain": ""
        },
        {
            "name": "x64-Debug",
            "generator": "Visual Studio 16 2019 Win64",
            "configurationType": "Debug",
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "",
            "ctestCommandArgs": "",
            "inheritEnvironments": [ "msvc_x64_x64" ],
            "variables": []
        }
    ]
}
</pre>

**Comment by troldal** [comment]
Hi @Juwong,

Sorry for the late reply. I have spent the past few months on an update to OpenXLSX. The dependencies pugixml and zippy are now bundled with OpenXLSX. The updated OpenXLSX source code has been pushed to the GitHub repo already.
