### ISSUE TITLE
The downloaded dependent library source code are empty files

### ISSUE THREAD

**Issue by Xiliusha** [troldal/OpenXLSX#54]
![图片](https://user-images.githubusercontent.com/40131112/87666677-a1679580-c79b-11ea-8b16-c941038a5007.png)
![图片](https://user-images.githubusercontent.com/40131112/87666682-a4fb1c80-c79b-11ea-88f3-81fabb57099a.png)
![图片](https://user-images.githubusercontent.com/40131112/87666691-a7f60d00-c79b-11ea-8835-0b97e97c05b6.png)
I have no idea to solve this problem. So I download all the files manually.

**Comment by UnknownObject000** [comment]
This issue also happened in my case.

**Comment by troldal** [comment]
Hi @Xiliusha,

The dependency libraries pugixml and zippy are now bundled with OpenXLSX, in order to avoid those kinds of issues.
Thanks for raising this issue.
