### ISSUE TITLE
The identifier "_mkdir" could not be found (ZipArchive.hpp)

### ISSUE THREAD

**Issue by Xiliusha** [troldal/OpenXLSX#55]
I tried to compile the project and found:
![图片](https://user-images.githubusercontent.com/40131112/87676833-a9c7cc80-c7ab-11ea-9074-ae48c2d5c24f.png)
After reviewing the Microsoft official  CRT documentation, I think this header file needed to include a header file:
![图片](https://user-images.githubusercontent.com/40131112/87677222-1773f880-c7ac-11ea-9052-10fedda0f097.png)

**Comment by troldal** [comment]
Hi @Xiliusha,

Sorry for the late reply.

Thank you for the input. I have now included the proper headers, so it should work out now.
The past few months, I have worked on an update of OpenXLSX. I have just pushed it to Github, and I have tested it on Windows, MacOS and Linux, so it should work without any errors now.
