### ISSUE TITLE
Compile error when compiling project

### ISSUE THREAD

**Issue by hsuwy1990** [troldal/OpenXLSX#57]
After finishing cmake configuration and try to build the project
I encounter the following error
OpenXLSX/library/implementation/headers/XLWorkbook_Impl.hpp:51:19: fatal error: variant: No such file or directory

it seems related to compiler version?
how to change the compiler version by cmake?

My building step
. download source code
. <project_home> mkdir build
. <project_home> cd build
. <project_home> cmake ..
. <project_home> make

**Comment by troldal** [comment]
Hi @hsuwy1990 

OpenXLSX works with GCC-7, Clang-8 and Visual Studio 2019 (and possibly 2017). If you don't have any of those installed, you need to do that first.

When you configure the project with CMake, use these options:
cmake -DCMAKE_CXX_COMPILER=path/to/compiler ..

**Comment by hsuwy1990** [comment]
Sorry for replying late
Many thanks for your information!
