### ISSUE TITLE
when I create a new xlsx file, then save, buf can't open with excel 2016. must repair it .

### ISSUE THREAD

**Issue by bxwpz** [troldal/OpenXLSX#58]

**Comment by troldal** [comment]
Hi @bxwpz 

Can you provide some more information, please?
- Compiler & version?
- Operating system (Windows, Linux, MacOS)?
- Sample code to recreate the issue?

I tried the following sample code, and had no issues:

```cpp
#include <OpenXLSX.hpp>
#include <iostream>

using namespace std;
using namespace OpenXLSX;

int main()
{
    XLDocument doc;
    doc.create("./Demo01.xlsx");
    doc.save();

    return 0;
}
```

I'm using Office 365... maybe it's more forgiving than Office 2016

**Comment by bxwpz** [comment]
thanks. no issues now .
