### ISSUE TITLE
Another C++ Excel library (xlnt)

### ISSUE THREAD

**Issue by openscript** [troldal/OpenXLSX#6]
There is one more library here on Github (https://github.com/tfussell/xlnt) which can be interesting.

**Comment by troldal** [comment]
I have recently become aware of it. I have tried it out and I think it is a very solid library. It probably also have fewer bugs than OpenXLSX. However, I found that XLNT had difficulties handling very large spreadsheets with up to 1 000 000 rows (this is indeed relevant, as in many companies, Excel is used as a poor-man's database system). OpenXLSX is much faster in handling large spreadsheets.

I have updated the README accordingly.

**Comment by Andrey111984** [comment]
The library has two big trivial problems:
-It consumes a lot of RAM. 
When reading Excel files over 12.8 MB - the XLNT library causes a "bad allocation" error, that is, the library simply does not work on files larger than 12-13 MB.
-When saving an Excel file, the XLNT library can damage excel file, and this happens by chance, when you do not wait.
