### ISSUE TITLE
OpenXLSX-Exports.hpp is missing

### ISSUE THREAD

**Issue by MikevanEerd** [troldal/OpenXLSX#63]
Hello,

I've tried to use this librairy, but the file "OpenXLSX-Exports.hpp" is missing. Therefore I can't build it. Even in the legacy branch I can't find the file. Could you upload this file so we could use this librairy. Thanks in advance!

Build error message:  
XLCell.hpp(54,10): fatal error C1083: Cannot open include file: 'OpenXLSX-Exports.hpp': No such file or directory

**Comment by CEXT-Dan** [comment]
I added my own file and export definition, but later I found there's a flag to generate the file. 
using visual studio, I found there were a couple of other compile errors using std17.
mostly just namespace ambiguities, pretty easy to work through.

**Comment by ovandara** [comment]
I have this issue using Xcode - can you please help me with how to use the flag to generate the  hpp?

**Comment by troldal** [comment]
Please note that OpenXLSX uses CMake as a build script generator. So the OpenXLSX-Export.hpp file is not missing; it will be automatically generated by CMake when running it.

Instructions for how to build OpenXLSX using CMake can be found on the GitHub page: https://github.com/troldal/OpenXLSX#build-instructions

Note that CMake support has been a part of Visual Studio since 2017, so it should be possible to open the project directly in Visual Studio. However, the OpenXLSX CMake project may use features not included in Visual Studio 2017. It works flawlessly in Visual Studio 2019 though.

**Comment by rz6955** [comment]
troldal, your instruction was not clear. Can you please put details step.

**Comment by ovandara** [comment]
I am probably missing something and apologize for being very basic at
programming.. ...
I followed my untuition in a sense and executed cmake twice....
I am not sure whether this was a success.

Could anyone please see the logs and whether I have deviated from the
instructions?

It may probably have to do with where I created the directory..

First LOG
1. All my projects reside in a directory I created called OV-PROJS
2. I downloaded the zip file into a subdirectory created called 'OpenXLSX'
under OV-PROJS
3. I assumed this is the root directory as referred to in the instructions
4. created directory called 'build' and executed 'cmake ..' > the below log
file

OV-MBP:build ovandara$ cmake ..

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)

Doxygen need to be installed to generate the doxygen documentation

-- Failed to find LLVM FileCheck

-- git Version: v1.5.2-bf585a27

-- Version: 1.5.2

-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile

-- Performing Test HAVE_STD_REGEX -- success

-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile

-- Performing Test HAVE_POSIX_REGEX -- success

-- Performing Test HAVE_STEADY_CLOCK -- success

-- Configuring done

-- Generating done

-- Build files have been written to:
/Users/ovandara/Documents/OV-PROJS/OpenXLSX/build

OV-MBP:build ovandara$

SECOND LOG:
1. As the above failed log file is referring to doxygen...
2. I found another directory called doxy which contained cmake lists
3. created 'build' subdirectory in 'doxy' and executed 'cmake ..' > below
log

-MBP:OpenXLSX ovandara$ cd doxy

OV-MBP:doxy ovandara$ mkdir build

OV-MBP:doxy ovandara$ cd build

OV-MBP:build ovandara$ cmake ..

CMake Warning (dev) in CMakeLists.txt:

  No project() command is present.  The top-level CMakeLists.txt file must

  contain a literal, direct call to the project() command.  Add a line of

  code such as


    project(ProjectName)


  near the top of the file, but after cmake_minimum_required().


  CMake is pretending there is a "project(Project)" command on the first

  line.

This warning is for project developers.  Use -Wno-dev to suppress it.


-- The C compiler identification is AppleClang 12.0.0.12000032

-- The CXX compiler identification is AppleClang 12.0.0.12000032

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working C compiler:
/Library/Developer/CommandLineTools/usr/bin/cc - skipped

-- Detecting C compile features

-- Detecting C compile features - done

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Check for working CXX compiler:
/Library/Developer/CommandLineTools/usr/bin/c++ - skipped

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)

Doxygen need to be installed to generate the doxygen documentation

CMake Warning (dev) in CMakeLists.txt:

  No cmake_minimum_required command is present.  A line of code such as


    cmake_minimum_required(VERSION 3.19)


  should be added at the top of the file.  The version specified may be
lower

  if you wish to support older CMake versions for this project.  For more

  information run "cmake --help-policy CMP0000".

This warning is for project developers.  Use -Wno-dev to suppress it.


-- Configuring done

-- Generating done

-- Build files have been written to:
/Users/ovandara/Documents/OV-PROJS/OpenXLSX/doxy/build

OV-MBP:build ovandara$

the directory structure:
[image: image.png]
------

**Comment by rz6955** [comment]
Hi troldal,

I wonder if your program works with office 365 excel?

Thanks

**Comment by franciscotovarmit** [comment]
I tried this library on ubuntu and it works fine.
 - create a folder  build
 - go inside build, then type (cmake dot dot),  cmake ..
 - type make
 - go to output folder
 - run examples  ./Demo1

When I tried to run the library on my own app (from another folder) is where I found the OpenXLSX-Exports.hpp issue but I can see is probably Im not configuring Cmake on my app properly.

**Comment by troldal** [comment]
@franciscotovarmit,

- When did you download the OpenXLSX repo? I just pushed changes to the master branch a few days ago, and you should use the most recent version.
- Can you attach the CMakeLists.txt file for your own project, so I can see what you are doing?

**Comment by franciscotovarmit** [comment]
> @franciscotovarmit,
> 
>     * When did you download the OpenXLSX repo? I just pushed changes to the master branch a few days ago, and you should use the most recent version.
> 
>     * Can you attach the CMakeLists.txt file for your own project, so I can see what you are doing?

Hi Troldal

I downloaded it a couple of weeks ago.

This is my CMakeLists.txt:
`
cmake_minimum_required(VERSION 3.0.0)
project(GetMarks)

find_package(OpenXLSX REQUIRED)

add_executable(GetMarks main.cpp)

target_include_directories(GetMarks PRIVATE ${})
target_link_libraries(GetMarks PRIVATE ${libOpenXLSX})

message("OpenXLSX Include Directories: "${OpenXLSX_INCLUDE_DIRS})
message("OpenXLSX Libraries: "${libOpenXLSX})`

**Comment by troldal** [comment]
Hi @franciscotovarmit,

I would recommend that you download the most recent version. You will notice that within the OpenXLSX repo, there is an OpenXLSX subfolder. This subfolder contains everything you need:

![image](https://user-images.githubusercontent.com/1604351/134472178-19ba1579-db8e-4a89-8cd0-3ffb2942b351.png)
 
I can see you have installed OpenXLSX using `make install`, or something like that. I would recommend that you copy the OpenXLSX folder and use it as a subdirectory in your own project. Then you can use `add_subdirectory` instead of `find_package`. The CMakeLists.txt file for your own project would then look something like this (no need to use `target_include_directories`; all the header files should be available automatically):

```cmake
cmake_minimum_required(VERSION 3.15)
project(GetMarks)
set(CMAKE_CXX_STANDARD 17)

add_subdirectory(OpenXLSX)

add_executable(GetMarks main.cpp)
target_link_libraries(GetMarks PRIVATE OpenXLSX::OpenXLSX)
```

**Comment by franciscotovarmit** [comment]
OK Trodal 
yes, thank you!  it works as you said.  I noticed some functions were updated too as my previous main.cpp was generating a dump error.

It amazing to be able create / extract excel data though C++ with a simple  

  `using` namespace OpenXLSX;``
