### ISSUE TITLE
openxlsx_export.h": No   such file or directory

### ISSUE THREAD

**Issue by OsPy303** [troldal/OpenXLSX#64]
I was trying to build the library OpenXLSX when I got this error:
mkdir build
cd build
cmake ..
make install

Install the project...
-- Install configuration: ""
CMake Error at library/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/user/Downloads/OpenXLSX-master/build/library/openxlsx_export.h": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)

make: *** [Makefile:86: install] Error 1

Can anyone help me please, i'm just a beginner.

**Comment by superyyf** [comment]
me too

**Comment by fndisme** [comment]
me too!
