### ISSUE TITLE
exception while opening .xlsx

### ISSUE THREAD

**Issue by vjGururaj7-star** [troldal/OpenXLSX#66]
Hi,
I am trying to read values form xlsx 

	const std::string filepath("D:/imgui/src/src/new.xlsx");
	const std::string sheetname("Sheet1");
	****m_XL_DocReadObj.open(filepath);****
	auto wks2 = m_XL_DocReadObj.workbook().worksheet(sheetname);
	strMin = wks2.cell(OpenXLSX::XLCellReference("A1")).value().asString();
	strMax = wks2.cell(OpenXLSX::XLCellReference("B1")).value().asString();
	m_XL_DocReadObj.close();

I am getting exception :: Microsoft C++ exception: std::length_error at memory location 0x0000006DB05FE5E0.
pls provide help on this

**Comment by sisco0** [comment]
Please, could you share your problematic Excel file?
I could run my application with your source code with no problem for my Excel file.
I suppose your folder is `src/src` as you mention.

**Comment by cgbsu** [comment]
Im having a similar problem, I think it may have something to do with the way I am including pugi? It wont build, saying it cant find the size of the pugi types, unless I put the pugi header after the OpenXLSX header.

**Comment by sisco0** [comment]
Please feel free to attach your file @cgbsu

**Comment by troldal** [comment]
Seems that this is no longer an issue, so I'm closing it.
