### ISSUE TITLE
Renaming sheet/worksheet

### ISSUE THREAD

**Issue by NemanjaGk** [troldal/OpenXLSX#72]
Dear,

I'm not sure if I'm doing something wrong, but after the commands written below, the page name doesn't change. 

std::cout << doc1.workbook().worksheetExists("Sheet1") << std::endl; // returns 1
if (doc1.workbook().worksheetExists("Sheet1")) {
doc1.workbook().sheet("Sheet1").setName("MySheet");
}
doc1.save();

Kind regards,
Nemanja

**Comment by troldal** [comment]
Apologise for the delay. The bug has been fixed now.
