### ISSUE TITLE
statically linking g++ on windows

### ISSUE THREAD

**Issue by braindaddy73** [troldal/OpenXLSX#73]
lib runs fine when dynamically linking. i think it is possible to static link? 
switching from ibOpenXLSX-shared to libOpenXLSX-static produces errors.
using codelite 15 with msys2-mingw-w64.
thx :)

**Comment by cgbsu** [comment]
Could you describe your errors a little more in detail?

**Comment by troldal** [comment]
The project has been updated. It will now build a shared ***or*** a static library, but not both. You can select which one in the CMakeLists.txt file.
