### ISSUE TITLE
Applying format

### ISSUE THREAD

**Issue by gvollant** [troldal/OpenXLSX#79]
Hello,

I did not find the way to get a cell content with format applied.

By example, get the "YYYY/MM/DD" or "DD/MM/YYYY" (as xlsx format choice) instead numeric (day from 1900 I believe)

**Comment by troldal** [comment]
OpenXLSX does not support formatting at the moment.
However, I have added a new class, XLDateTime, that can convert Excel date/time serial numbers. See Demo01 for details.
