### ISSUE TITLE
Bad header when using external libzip++

### ISSUE THREAD

**Issue by egorpugin** [troldal/OpenXLSX#8]
In file `@library\@openxlsx\implementation\sources\XLDocument_Impl.cpp`
`#include <libzip++.h>` must be `#include <libzippp.h>`

**Comment by troldal** [comment]
The libzip++.h and lib zip..cpp are both included in the repository. The CMake script will copy the header file to the build directory.

Changing to libzippp.h is probably locating a header file present on your system already.

Please ensure that the CMake script is run properly.

**Comment by egorpugin** [comment]
I'm running my own build system and not using your bundled libs.
In general this case also should work.

**Comment by troldal** [comment]
I have now embedded the libzippp library in OpenXLSX. That should solve the issue.

**Comment by egorpugin** [comment]
I see. Thank you.
