### ISSUE TITLE
bad_variant_access error

### ISSUE THREAD

**Issue by vlsireddy** [troldal/OpenXLSX#81]
Hi,
   I faced one more error.

a xlsx file re-opened always lands into this error bad_variant_access() 

as part of this code
            if constexpr (std::is_same<T, XLWorksheet>::value)
                return std::get<XLWorksheet>(m_sheet);
here the xlsx file is created by create() option. 

a manually created file does not create such error when re-opened. 

i ensured permissions and others, both are same.

**Comment by kevinofsias** [comment]
open XLContentTypes.cpp file，and make sure the string in GetTypeFromString function and GetStringFromType function are the same.there are some error spelling in GetStringFromType function.
