### ISSUE TITLE
Installing the project does not seem to work

### ISSUE THREAD

**Issue by qlands** [troldal/OpenXLSX#82]
I trying to install the library and the include files in my Ubuntu but the install fails with the message:

cannot find /home/cquiros/temp/OpenXLSX/build/library/openxlsx_export.h

If I fixed to be OpenXLSX-Exports.hpp the install passes but only installs:

```
-- Installing: /usr/local/include/openxlsx/OpenXLSX-Exports.hpp
-- Installing: /usr/local/lib/libOpenXLSX-static.a
-- Installing: /usr/local/lib/libOpenXLSX-shared.so
-- Installing: /usr/local/lib/cmake/openxlsx/OpenXLSXConfig.cmake
-- Installing: /usr/local/lib/cmake/openxlsx/OpenXLSXConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/openxlsx/OpenXLSXTargets.cmake
-- Installing: /usr/local/lib/cmake/openxlsx/OpenXLSXTargets-noconfig.cmake
```

How can I make the install to install OpenXLSX.hpp so I can use the library in my project?

**Comment by troldal** [comment]
The installation should work now.
However, the easiest way to use OpenXLSX is to include it as a subfolder in your CMake project.
