### ISSUE TITLE
Zippy::ZipRuntimeError

### ISSUE THREAD

**Issue by WinSure** [troldal/OpenXLSX#83]
When I try to parse a local existing XLSX file, running the demo4 program will report an error crash.
[Demo04.xlsx](https://github.com/troldal/OpenXLSX/files/6552509/Demo04.xlsx)

**Comment by WinSure** [comment]
This is the error screenshot
![image](https://user-images.githubusercontent.com/28434050/119797385-c4f78280-bf0c-11eb-91e4-0ee3a9a61ca2.png)

**Comment by brainfk123** [comment]
Probably because the file isn't found, check your relative path or use a absolute path

**Comment by hqber** [comment]
我也遇到了，请问是如何解决的吗？？

**Comment by troldal** [comment]
This is almost certainly due to some problem with Unicode on Windows.

Try downloading the latest version and (very important!) read build instructions and the section about Unicode in the README file.

**Comment by hqber** [comment]
@troldal 这个问题，我解决了，路径权限的问题， 如果路径权限没问题，我之前是用C语言的open函数，尝试切换C++试试
