### ISSUE TITLE
Missing <algorithm> in XLColor_Impl.cpp

### ISSUE THREAD

**Issue by egorpugin** [troldal/OpenXLSX#9]
`@openxlsx\implementation\sources\XLColor_Impl.cpp` uses min() calls from std but no header provided.

**Comment by troldal** [comment]
Thanks for that. I have added the <algorithm> header.

The XLColor class is not used for anything yet. In the future, OpenXLSX should support setting spreadsheet formatting, incl. colors, but this has not been implemented yet.
