### ISSUE TITLE
Cannot read from sheet(i.e. column count)

### ISSUE THREAD

**Issue by praudmur** [troldal/OpenXLSX#92]
Hello!
I am trying to read column count and can't - columnCount() returns 1 while it should return 7.
Attaching the code and the file.

`
	XLDocument doc;
	XLWorksheet sheet;
	XLCell cell;

	int iTotalSheets = 0;
	int iTotalRows = 0;
	int iTotalColumns = 0;

	doc.open(g_ReestrOrdersPath);
	logger->info("Opened");

	iTotalSheets = doc.workbook().worksheetCount();
	logger->info("Sheet count is {}", iTotalSheets);

	for (const auto& s_WorksSheetName : doc.workbook().worksheetNames())
	{

		logger->info("Processing iSheet::{}", s_WorksSheetName);

		sheet = doc.workbook().worksheet(s_WorksSheetName);
		iTotalRows = sheet.rowCount();
		iTotalColumns = sheet.columnCount();
		logger->info(" Total columns {}", iTotalColumns);
		logger->info("Total rows {}", iTotalRows);
        }

`
Log output:

```
[2021-08-24 14:06:46.083] [basic_logger] [info] Opened
[2021-08-24 14:06:46.083] [basic_logger] [info] Sheet count is 2
[2021-08-24 14:06:46.083] [basic_logger] [info] Processing iSheet::Temp1
[2021-08-24 14:06:46.083] [basic_logger] [info]  Total columns 1
[2021-08-24 14:06:46.083] [basic_logger] [info] Total rows 1
[2021-08-24 14:06:46.083] [basic_logger] [info] Processing iSheet::Temp2
[2021-08-24 14:06:46.083] [basic_logger] [info]  Total columns 1
[2021-08-24 14:06:46.083] [basic_logger] [info] Total rows 0
```

[Reestr_TEST.xlsx](https://github.com/troldal/OpenXLSX/files/7038640/Reestr_TEST.xlsx)

**Comment by troldal** [comment]
Hi @praudmur,

It's been fixed now. The solution is a bit brute force but it works. I may look into a more elegant solution in the future.

**Comment by praudmur** [comment]
Thanks.
I've rebuilt the library and getting this error

Is this something on my end?(errors below).

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'valueType': is not a member of 'OpenXLSX::XLCell'	uiaction	D:\VSProjects\uiaction\ExcelWork.h	250	
Error	C2039	'valueType': is not a member of 'OpenXLSX::XLCell'	uiaction	D:\VSProjects\uiaction\ExcelWork.h	352	
Error (active)	E0135	class "OpenXLSX::XLCell" has no member "valueType"	uiaction	D:\VSProjects\uiaction\ExcelWork.h	250	
Error (active)	E0135	class "OpenXLSX::XLCell" has no member "valueType"	uiaction	D:\VSProjects\uiaction\ExcelWork.h	352

**Comment by troldal** [comment]
It looks like you are trying to call a valueType() method on an XLCell object, but that won't work. You have to call the XLCell::value() method, which will return an XLCellValue object. On the XLCellValue object, you can call the type() method, which will give you what you want.
