### ISSUE TITLE
Gibberish instead of cyrillic symbols

### ISSUE THREAD

**Issue by praudmur** [troldal/OpenXLSX#93]
Hello again!

I cannot extract cyrillic symbols from Excel file.
Excel file attached, output attached. 
Nor char extraction, not string work.
Latin symbols are extracted fine.

`

        m_text->AppendText("\nНачинаю поиск.");
	XLDocument doc;
	XLWorksheet sheet;
	XLCell cell;

	int iTotalSheets = 0;
	int iTotalRows = 0;
	int iTotalColumns = 0;

	int iRow = 1;
	int iCol = 1;

	string s_TempText;

	doc.open(g_ReestrOrdersPath);
	logger->info("Opened");

	iTotalSheets = doc.workbook().worksheetCount();
	logger->info("Sheet count is {}", iTotalSheets);

	for (const auto& s_WorksSheetName : doc.workbook().worksheetNames())
	{

		logger->info("Processing iSheet::{}", s_WorksSheetName);

		sheet = doc.workbook().worksheet(s_WorksSheetName);

		iTotalRows = sheet.rowCount();
		iTotalColumns = sheet.columnCount();
		logger->info(" Total columns {}", iTotalColumns);
		logger->info("Total rows {}", iTotalRows);

		while (iCol <= iTotalColumns)
		{
			logger->info("Checking COL# {}", iCol);
			cell = sheet.cell(1, iCol);

			char s_text[4000]{};

			strcpy(s_text, sheet.cell(iRow, iCol).value().get<string>().c_str());
			s_TempText = sheet.cell(iRow, iCol).value().get<string>();

			logger->info("Text is {}", s_text);
			Frame_Main->m_text->AppendText(s_text);
		}
	}

`

[Reestr_TEST.xlsx](https://github.com/troldal/OpenXLSX/files/7041630/Reestr_TEST.xlsx)

Output:
Начинаю поиск.РќРѕРјРµСЂ РїСЂРёРєР°Р·Р°Р”Р°С‚Р° РїСЂРёРєР°Р·Р°Р¤РРћРљРѕРјРјРµРЅС‚Р°СЂРёР№РџРѕРґРїРёСЃР°РЅР’ РїР°РїРєРµРћС‚РїСЂР°РІРёР» РІ Р±СѓС…РіР°Р»С‚РµСЂРёСЋ

**Comment by troldal** [comment]
Did you read the README file? I particular the section on UNICODE?

One paragraph says:

> Note also that while UTF-8 is well supported on Linux and MacOS, support
on Windows is more limited. For example, output of non-ASCII characters
(e.g. Chinese or Japanese characters) to the terminal window will look
like gibberish.

I suspect that you logger outputs text to the windows terminal, which does not work well with non-ASCII UTF-8 characters. Try outputting to a text file and open it in an editor that supports UTF-8 (for example Atom).

**Comment by praudmur** [comment]
Yes, I've read that paragraph.
My output contains "Начинаю поиск" which is a cyryllic phrase. And in the same output strings are not displayed well.

Indeed I could succesfully read  .txt file output with Atom but everywhere else cannot work with these strings for some reason.

Even find() function doesn't detect cyrillic test

```
			std::size_t found;

			found = s_TempText.find("Номер"); // this word is in the first column - Cell(1;1)

			if (found != std::string::npos)
			{
				logger->info("FOUND NOMER PRIKAZA");
			}
```

**Comment by praudmur** [comment]
I'll try to convert text using your suggestions.

**Comment by troldal** [comment]
You have my sympathies. Dealing with Unicode on Windows is a giant headache. In addition to Boost.Nowide or Boost.Text as suggested in the README file, you can also try your luck with [miniutf](https://github.com/dropbox/miniutf) by Dropbox. It's a small set of utilities for converting between different text encodings.

**Comment by CEXT-Dan** [comment]
FYI, I use these functions for converting in windows, it reads your xlsx file fine

`
inline std::wstring utf8_to_wstr(const std::string& utf8) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> wcu8;
    return wcu8.from_bytes(utf8);
}

inline std::string wstr_to_utf8(const std::wstring& utf16) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> wcu8;
    return wcu8.to_bytes(utf16);
}
`

**Comment by troldal** [comment]
@CEXT-Dan,

Thanks for your input. However, please bear in mind that this method is deprecated in C++17 (see https://en.cppreference.com/w/cpp/locale/wstring_convert).

**Comment by praudmur** [comment]
@troldal 

>But are you sure this error occurs because of non-ASCII filenames? What happens if you use an ASCII filename?
If I use english-only path, then library works fine.

I tried to debug further it but unfortunately I could not.
I also tried converting string to UTF-8 using suggestion from stackoverflow and still got the error.
So I ended up using your described method of temporarily copying the file in program folder.
If in the future you'll need me to  test a possible fix - feel free to ping me.

**Comment by troldal** [comment]
Hi @praudmur,

I just pushed an update to the dev branch.
Can I ask you to try to see if it solves your problems with non-ASCII filenames?

**Comment by praudmur** [comment]
@troldal hey!
With the new version I can't compile.
The error is:


Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class OpenXLSX::XLCell __thiscall OpenXLSX::XLWorksheet::cell(unsigned int,unsigned short)" (__imp_?cell@XLWorksheet@OpenXLSX@@QAE?AVXLCell@2@IG@Z) referenced in function "bool __cdecl f_Excel_Process_File(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,int)" (?f_Excel_Process_File@@YA_NV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@H@Z)	uiaction	D:\VSProjects\uiaction\uiaction.obj	1

**Comment by troldal** [comment]
Hi @praudmur,

Thanks for trying it out.

LNK2019 is a linker error, not a compile error. It means that your function 'f_Excel_Process_File' cannot find OpenXLSX::XLWorksheet::cell function. 

Are you sure you have added OpenXLSX to the list of link libraries?
If you use CMake for your own project, do you mind sending the CMakeLists.txt file, so I can have a look?

**Comment by praudmur** [comment]
Hello @troldal!
[CMakeCache.txt](https://github.com/troldal/OpenXLSX/files/7121382/CMakeCache.txt)

Sorry for the delay. Sending the file.
All I did was to replace old libraries with new generated ones.Old ones had the same name and were previously linked. The code which compiled on old libraries, doesn't compile on the new one.

**Comment by praudmur** [comment]
@troldal 
Hi!

Firstly, I managed to fix the issue on my old version using this function(this converts string filepath). Hope this will come in handy in case someone else is having the same issue.

`string f_to_UTF8(std::string codepage_str)
{

    int size = MultiByteToWideChar(CP_ACP, MB_COMPOSITE, codepage_str.c_str(), codepage_str.length(), nullptr, 0);
    std::wstring utf16_str(size, '\0');
    MultiByteToWideChar(CP_ACP, MB_COMPOSITE, codepage_str.c_str(), codepage_str.length(), &utf16_str[0], size);

    int utf8_size = WideCharToMultiByte(CP_UTF8, 0, utf16_str.c_str(), utf16_str.length(), nullptr, 0, nullptr, nullptr);
    std::string utf8_str(utf8_size, '\0');
    WideCharToMultiByte(CP_UTF8, 0, utf16_str.c_str(), utf16_str.length(), &utf8_str[0], utf8_size, nullptr, nullptr);
    return utf8_str;
}`

secondly, I have abovementioned issue with "unresolved extensials" on the new, 0.31 version.
I build it for x64(as my program is) and replaced my old library which was linked(had to change the library name to OpenXLSX.lib). In case you have any thoughts, I'll be happy if you share them with me.
Uploading some cmake files.

Also I'd like to mention that recently I moved to static library instead of shared. For static library to work I had to change OpenXLSX-Exports.hpp by adding "#define OPENXLSX_STATIC_DEFINE". When I tried new version, I temporarily removed the line and still got "unresolved external symbol" error.

[build.zip](https://github.com/troldal/OpenXLSX/files/7190685/build.zip)
.

**Comment by troldal** [comment]
Hi @praudmur,

Please note that I pushed a new version to the master branch last night. I did a lot of changes to the file structure. Also, you can now build a shared ***or*** a static library, but not both. You can select which one, in the CMakeLists.txt file in the OpenXLSX subdirectory.  

I find it really strange that you have problems with the 'unresolved external symbols' error. It means that your program does not link properly to the OpenXLSX library. One reason I can think of is that you may be trying to ling your program in DEBUG mode, to the OpenXLSX library built in RELEASE mode. This will not work on Windows, so you should make sure that your program is built with the same configuration as the library (ie. both DEBUG or both RELEASE etc.)

**Comment by praudmur** [comment]
> 
> 
> Hi @praudmur,
> 
> Please note that I pushed a new version to the master branch last night. I did a lot of changes to the file structure. Also, you can now build a shared _**or**_ a static library, but not both. You can select which one, in the CMakeLists.txt file in the OpenXLSX subdirectory.
> 
> I find it really strange that you have problems with the 'unresolved external symbols' error. It means that your program does not link properly to the OpenXLSX library. One reason I can think of is that you may be trying to ling your program in DEBUG mode, to the OpenXLSX library built in RELEASE mode. This will not work on Windows, so you should make sure that your program is built with the same configuration as the library (ie. both DEBUG or both RELEASE etc.)

yes, I was using the new version. This issue was on my part - I think I didn't update headers correctly, latest version compiles now. Looking forward to testing new features.

**Comment by troldal** [comment]
Glad to hear it works for you now 😀
