### ISSUE TITLE
how to batch operation excel?

### ISSUE THREAD

**Issue by xinsuinizhuan** [troldal/OpenXLSX#94]
I want to export the data from database to a excel, and inport the data from excel to my software database.hou to operate?

**Comment by xinsuinizhuan** [comment]
like this, i fisrt insert a table head, then i bash insert a record:
rercord should 10 cols and n rows
![图片](https://user-images.githubusercontent.com/40679769/131198132-217c1914-f5e5-4a23-a394-cdf0b77add72.png)

**Comment by xinsuinizhuan** [comment]
Others, when i write a chinese char to table,  then when i open the file, it break, tell me the table has some wrong with it:
![图片](https://user-images.githubusercontent.com/40679769/131199665-87b914a4-8767-4637-aa52-9b3928516877.png)
![图片](https://user-images.githubusercontent.com/40679769/131199704-15a5fb06-9103-4ee3-9318-db937cdb3ecb.png)

**Comment by xinsuinizhuan** [comment]
my cpp file format is not utf8, it is utf8-rom

**Comment by troldal** [comment]
All input to OpenXLSX must be in UTF8. The code I can see on the screenshot should work, so you must be using a wrong text encoding (not UTF8). Before working any further on this, you should take some time to understand Unicode and the differences between UTF8, UTF16, UTF32, UCS2, Windows code pages etc.

I recommend these sources:

https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/

https://youtu.be/n0GK-9f4dl8

I cannot help you any further.
