### ISSUE TITLE
my excel cell char is a time,like:2021/8/22  14:47:43,but when i get it, it is a float type, I only want get the time string

### ISSUE THREAD

**Issue by xinsuinizhuan** [troldal/OpenXLSX#97]
My excel cell char is a time string,like: 2021/8/22  14:47:43, when i get it, it it a float type, the the value is: 44430.61xxx，I only want get the time string, how should i do?

**Comment by metorm** [comment]
This seems like an interesting question. I really want to know how Excel itself knows whether it is a floating point number or a time stored in a cell.

**Comment by CEXT-Dan** [comment]
> This seems like an interesting question. I really want to know how Excel itself knows whether it is a floating point number or a time stored in a cell. 

It’s in the style, some the built-in types are documented here
(https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1)

If its custom, you can parse the format string, iterate the format string, once you start finding Y M D H S AM/PM, you know it’s a date,  Use this for all custom formats, currency, precision, thousandths separator etc.

**Comment by metorm** [comment]
> > This seems like an interesting question. I really want to know how Excel itself knows whether it is a floating point number or a time stored in a cell.
> 
> It’s in the style, some the built-in types are documented here (https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1)
> 
> If its custom, you can parse the format string, iterate the format string, once you start finding Y M D H S AM/PM, you know it’s a date, Use this for all custom formats, currency, precision, thousandths separator etc.

OK ... what a real pain in the ass ...
